doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\SliderBundle\Model\SliderInterface: Enhavo\Bundle\SliderBundle\Entity\Slider

enhavo_app:
    template_paths:
        enhavo_slider:
            path: '@EnhavoSliderBundle/Resources/views'
            priority: 10
    roles:
        enhavo_slider_slide_index:
            role: ROLE_ENHAVO_SLIDER_SLIDE_INDEX
            label: slide.role.label.index
            translationDomain: EnhavoSliderBundle
        enhavo_slider_slide_create:
            role: ROLE_ENHAVO_SLIDER_SLIDE_CREATE
            label: slide.role.label.create
            translationDomain: EnhavoSliderBundle
        enhavo_slider_slide_update:
            role: ROLE_ENHAVO_SLIDER_SLIDE_UPDATE
            label: slide.role.label.update
            translationDomain: EnhavoSliderBundle
        enhavo_slider_slide_delete:
            role: ROLE_ENHAVO_SLIDER_SLIDE_DELETE
            label: slide.role.label.delete
            translationDomain: EnhavoSliderBundle