parameters:
    enhavo_slider.form.type.slider_order.class: Enhavo\Bundle\SliderBundle\Form\Type\SlideOrderType

services:
    enhavo_slider_slide_order:
        class: '%enhavo_slider.form.type.slider_order.class%'
        arguments:
            - '%enhavo_slider.model.slide.class%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\SliderBundle\Form\Type\SlideType:
        arguments:
            - '%enhavo_slider.model.slide.class%'
        tags:
            - { name: form.type, alias: enhavo_slider_slide }

    Enhavo\Bundle\SliderBundle\Form\Type\SliderType:
        arguments:
            - '%enhavo_slider.model.slider.class%'
        tags:
            - { name: form.type, alias: enhavo_slider_slider }

    Enhavo\Bundle\SliderBundle\Widget\SliderWidgetType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: slider }

    Enhavo\Bundle\SliderBundle\Menu\SliderMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\SliderBundle\Menu\SlideMenu:
        tags:
            - { name: enhavo_app.menu }

    enhavo_slider.factory.slide:
        class: '%enhavo_slider.factory.slide.class%'
        arguments:
            - '%enhavo_slider.model.slide.class%'
            - '@enhavo_slider.repository.slider'

    Enhavo\Bundle\SliderBundle\Block\SliderBlockType:
        arguments:
            - '@enhavo_slider.repository.slide'
        tags:
            - { name: enhavo_block.block }
