parameters:
    enhavo_slider.form.type.slider_order.class: Enhavo\Bundle\SliderBundle\Form\Type\SlideOrderType

services:
    enhavo_slider_slide_order:
        class: '%enhavo_slider.form.type.slider_order.class%'
        arguments:
            - '%enhavo_slider.model.slide.class%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\SliderBundle\Form\Type\SlideType:
        arguments:
            - '%enhavo_slider.model.slide.class%'
            - '%enhavo_app.translate%'
        tags:
            - { name: form.type, alias: enhavo_slider_slide }

    Enhavo\Bundle\SliderBundle\Form\Type\SliderType:
        arguments:
            - '%enhavo_slider.model.slider.class%'
        tags:
            - { name: form.type, alias: enhavo_slider_slider }

    enhavo_slider_slider.widget.slider:
        class: Enhavo\Bundle\SliderBundle\Widget\SliderWidget
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: slider }


    enhavo_slider.extend_listener.slider:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\SliderBundle\Entity\Slider
            - '%enhavo_slider.model.slider.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_slider.extend_listener.slide:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\SliderBundle\Entity\Slide
            - '%enhavo_slider.model.slide.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Enhavo\Bundle\SliderBundle\Menu\SliderMenu:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: slider }