Enhavo\Bundle\ContentGridBundle\Entity\Container:
    type: entity
    table: content_container
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        type:
            type: string
            length: 255
            nullable: true

        configuration:
            type: blob
            nullable: true

    oneToMany:
        columns:
            targetEntity: Column
            mappedBy: container
            cascade: ['persist', 'refresh', 'remove']

    manyToOne:
        content:
            targetEntity: Content

        column:
            targetEntity: Column

    lifecycleCallbacks: {  }
