enhavo_project_demo_index:
    path: /
    defaults:
        _controller: EnhavoProjectBundle:Demo:index
        _method: GET

enhavo_project_demo_media:
    path: /media
    defaults:
        _controller: EnhavoProjectBundle:Demo:media
        _method: GET

enhavo_project_demo_grid:
    path: /grid
    defaults:
        _controller: EnhavoProjectBundle:Demo:grid
        _method: GET

enhavo_project_demo_navigation:
    path: /navigation
    defaults:
        _controller: EnhavoProjectBundle:Demo:navigation
        _method: GET