enhavo_slider_slider_index:
    options:
        expose: true
    path: /enhavo/slider/slider/index
    methods: [GET]
    defaults:
        _controller: enhavo_slider.controller.slider::indexAction
        _sylius:
            viewer:
                label: slider.label.slider
                translation_domain: EnhavoSliderBundle
                open_route: enhavo_slider_slide_index

enhavo_slider_slider_create:
    options:
        expose: true
    path: /enhavo/slider/slider/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_slider.controller.slider::createAction
        _sylius:
            redirect: enhavo_slider_slider_update
            viewer:

enhavo_slider_slider_update:
    options:
        expose: true
    path: /enhavo/slider/slider/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_slider.controller.slider::updateAction
        _sylius:
            viewer:

enhavo_slider_slider_table:
    options:
        expose: true
    path: /enhavo/slider/slider/table
    methods: [GET,POST]
    defaults:
        _controller: enhavo_slider.controller.slider::tableAction
        _sylius:
            paginate: false
            viewer:
                translation_domain: EnhavoSliderBundle
                columns:
                    title:
                        property: title
                        width: 10
                        label: slider.label.title
                        type: property
                    action:
                        width: 2
                        label: label.edit
                        translation_domain: EnhavoAppBundle
                        type: action
                        action:
                            type: update
                            route: enhavo_slider_slider_update

enhavo_slider_slider_delete:
    options:
        expose: true
    path: /enhavo/slider/slider/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_slider.controller.slider::deleteAction

enhavo_slider_slider_preview:
    options:
        expose: true
    path: /enhavo/slider/slider/preview
    methods: [GET]
    defaults:
        _controller: enhavo_slider.controller.slider::previewAction
        _sylius:
            viewer:

enhavo_slider_slider_resource_preview:
    options:
        expose: true
    path: /enhavo/slider/slider/resource/preview
    methods: [POST]
    defaults:
        _controller: enhavo_slider.controller.slider::previewResourceAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_article.controller.article:showResourceAction

