services:
    Enhavo\Bundle\ArticleBundle\Form\Type\ArticleType:
        arguments:
            - '%enhavo_article.model.article.class%'
            - [default]
        tags:
            - { name: form.type, alias: enhavo_article_article }

    enhavo_article.extend_listener.article:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\ArticleBundle\Entity\Article
            - '%enhavo_article.model.article.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Enhavo\Bundle\ArticleBundle\Menu\ArticleRootMenuType:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\ListMenu
        tags:
            - { name: enhavo.menu, alias: article }

    Enhavo\Bundle\ArticleBundle\Menu\ArticleMenuType:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: article_article }

    Enhavo\Bundle\ArticleBundle\Menu\TagMenuType:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: article_tag }

    Enhavo\Bundle\ArticleBundle\Menu\CategoryMenuType:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: article_category }

    enhavo_article.statistic.article:
        class: Enhavo\Bundle\ArticleBundle\Statistic\ArticleStatistic
        calls:
          - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.statistic, alias: article }

    Enhavo\Bundle\ArticleBundle\Block\ArticleListBlockType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.block, alias: article_list }

    Enhavo\Bundle\ArticleBundle\Block\ArticleTeaserBlockType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.block, alias: article_teaser }

    Enhavo\Bundle\ArticleBundle\Widget\ArticleListType:
        public: true
        arguments:
            - '@enhavo_article.repository.article'
            - '@request_stack'
        tags:
            - { name: enhavo.widget, alias: article_list }

    Enhavo\Bundle\ArticleBundle\Controller\ArticleController:
        public: true
        arguments:
            - '@Enhavo\Bundle\CommentBundle\Comment\CommentManager'
        calls:
            - [setContainer, ['@service_container']]

    enhavo_article.factory.article:
        public: true
        class: '%enhavo_article.factory.article.class%'
        arguments:
            - '%enhavo_article.model.article.class%'
            - '@enhavo_block.factory.node'
            - '@Enhavo\Bundle\RoutingBundle\Factory\RouteFactory'
            - '@enhavo_media.factory.file'

