Enhavo\Bundle\ArticleBundle\Entity\Article:
    properties:
        title:
            - NotBlank:
                groups: [default]
        content:
            - Valid:
                groups: [default]
