enhavo_newsletter:
    newsletter:
        mail:
            from: '%env(string:MAILER_FROM)%'
        templates:
            default:
                template: 'mail/newsletter/template/default.html.twig'
                label: newsletter.label.default
                translation_domain: EnhavoNewsletterBundle
    strategy:
        settings:
            notify:
                from: '%env(string:MAILER_FROM)%'
                admin_email: '%env(string:MAILER_TO)%'
                sender_name: '%env(string:MAILER_NAME)%'
            accept:
                from: '%env(string:MAILER_FROM)%'
                admin_email: '%env(string:MAILER_TO)%'
                sender_name: '%env(string:MAILER_NAME)%'
            double_opt_in:
                from: '%env(string:MAILER_FROM)%'
                admin_email: '%env(string:MAILER_TO)%'
                sender_name: '%env(string:MAILER_NAME)%'
    forms:
        default:
            type: enhavo_newsletter_subscribe
            template: EnhavoNewsletterBundle:Subscriber:subscribe.html.twig

enhavo_app:
    template_paths:
        enhavo_newsletter:
            path: '@EnhavoNewsletterBundle/Resources/views'
            priority: 10
    roles:
        enhavo_newsletter_subscriber_index:
            role: ROLE_ENHAVO_NEWSLETTER_SUBSCRIBER_INDEX
            label: subscriber.role.label.index
            translation_domain: EnhavoNewsletterBundle
        enhavo_newsletter_subscriber_create:
            role: ROLE_ENHAVO_NEWSLETTER_SUBSCRIBER_CREATE
            label: subscriber.role.label.create
            translation_domain: EnhavoNewsletterBundle
        enhavo_newsletter_subscriber_update:
            role: ROLE_ENHAVO_NEWSLETTER_SUBSCRIBER_UPDATE
            label: subscriber.role.label.update
            translation_domain: EnhavoNewsletterBundle
        enhavo_newsletter_subscriber_delete:
            role: ROLE_ENHAVO_NEWSLETTER_SUBSCRIBER_DELETE
            label: subscriber.role.label.delete
            translation_domain: EnhavoNewsletterBundle

        enhavo_newsletter_newsletter_index:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_INDEX
            label: newsletter.role.label.index
            translation_domain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_create:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_CREATE
            label: newsletter.role.label.create
            translation_domain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_update:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_UPDATE
            label: newsletter.role.label.update
            translation_domain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_delete:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_DELETE
            label: newsletter.role.label.delete
            translation_domain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_send:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_SEND
            label: newsletter.role.label.send
            translation_domain: EnhavoNewsletterBundle
        enhavo_newsletter_newsletter_view:
            role: ROLE_ENHAVO_NEWSLETTER_NEWSLETTER_VIEW
            label: newsletter.role.label.view
            translation_domain: EnhavoNewsletterBundle

enhavo_block:
    render:
        sets:
            newsletter:
                picture: EnhavoNewsletterBundle:Theme\Block:picture.html.twig
                picture_picture: EnhavoNewsletterBundle:Theme\Block:picture_picture.html.twig
                three_picture: EnhavoNewsletterBundle:Theme\Block:three_picture.html.twig
                gallery: EnhavoNewsletterBundle:Theme\Block:gallery.html.twig
                text: EnhavoNewsletterBundle:Theme\Block:text.html.twig
                text_picture: EnhavoNewsletterBundle:Theme\Block:text_picture.html.twig
                text_text: EnhavoNewsletterBundle:Theme\Block:text_text.html.twig
                cite_text: EnhavoNewsletterBundle:Theme\Block:cite_text.html.twig
                download: EnhavoNewsletterBundle:Theme\Block:download.html.twig
                video: EnhavoNewsletterBundle:Theme\Block:video.html.twig

enhavo_routing:
    classes:
        Enhavo\Bundle\NewsletterBundle\Entity\Newsletter:
            router:
                default:
                    type: slug
                admin:
                    type: id
                    route: enhavo_newsletter_newsletter_update
            generators:
                slug:
                    type: slug
                    property: title

doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\NewsletterBundle\Model\SubscriberInterface: Enhavo\Bundle\NewsletterBundle\Entity\Subscriber
            Enhavo\Bundle\NewsletterBundle\Model\GroupInterface: Enhavo\Bundle\NewsletterBundle\Entity\Group
            Enhavo\Bundle\NewsletterBundle\Model\NewsletterInterface: Enhavo\Bundle\NewsletterBundle\Entity\Newsletter
