enhavo_grid_item_form:
    path:  /enhavo/grid/form
    defaults:
        _controller: EnhavoFormBundle:DynamicForm:item
        _resolver: enhavo_grid.resolver.item_resolver
    options:
        expose: true