#parameters:
#    locale: en

enhavo_app:
    menu:
        dashboard:
            type: dashboard
        user:
            type: user
        article:
            type: article
        page:
            type: page
        slider:
            type: slider
        newsletter:
            type: newsletter
        calendar:
            type: calendar
#        shop:
#            type: shop
        navigation:
            type: navigation
        redirect:
            type: redirect
        media_library:
            type: media_library
        sidebar:
            type: sidebar
        template:
            type: template
        theme:
            type: theme


enhavo_block:
    blocks:
        picture:
            type: picture
        gallery:
            type: gallery
        text:
            type: text
        text_picture:
            type: text_picture
        blockquote:
            type: blockquote
        video:
            type: video
        one_column:
            type: one_column
        two_column:
            type: two_column
        three_column:
            type: three_column
        article_stream:
            type: article_stream
        sidebar_column:
            type: sidebar_column
        template:
            type: template
        resource:
            type: resource
        contact:
            type: contact

