enhavo_media:
    filter:
        video_image:
            ffmpeg_path: /usr/bin/ffmpeg
            ffprobe_path: /usr/bin/ffprobe
    formats:
        articleThumbnail:
            type: image
            width: 350
            height: 350
        sliderHero:
            type: image
            width: 1300
            height: 600
        magazine_cover:
            type: image
            width: 1300
            height: 600
        person_image:
            type: image
            width: 500
            height: 500
    form:
        default:
            actions:
                media_library:
                    type: media_library_open_select
when@dev:
    enhavo_media:
        file_not_found:
            handler: Enhavo\Bundle\MediaBundle\FileNotFound\CreateDummyFileNotFoundHandler