language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
    - composer self-update
    - if [[ ! -z "$GITHUB_OAUTH_TOKEN" ]]; then composer config -g github-oauth.github.com "$GITHUB_OAUTH_TOKEN" >/dev/null 2>&1; fi

install:
    - sudo apt-get install -y --force-yes php5-mysql
    - mysql -e 'create database enhavo_test'
    - composer install --no-interaction

before_script:
    - app/console cache:warmup --env=test --no-debug
    - app/console doctrine:schema:create --env=test
    - app/console assets:install --env=test --no-debug
    - app/console assetic:dump --env=test --no-debug

    - php -v
    - php -i | grep -v GITHUB_OAUTH_TOKEN

script:
  - composer validate
  - bin/behat --strict