language: php

dist: xenial

php:
  - 7.2

services:
  - mysql

env:
  - ENVIRONMENT=test DEBUG=true

before_install:
    - composer self-update
    - if [[ ! -z "$GITHUB_OAUTH_TOKEN" ]]; then composer config -g github-oauth.github.com "$GITHUB_OAUTH_TOKEN" >/dev/null 2>&1; fi
    - export USE_ZEND_ALLOC=0
    
install:
    - sudo apt-get install -y --force-yes php-mysql
    - sudo apt-get install -y --force-yes npm
    - sudo npm install -g yarn
    - mysql -e 'create database enhavo_test'
    - composer install --no-interaction --optimize-autoloader --prefer-dist

before_script:
    - bin/console cache:warmup --env=test --no-debug
    - bin/console doctrine:migration:migrate --env=test --no-interaction
    - tests/bin/console doctrine:schema:update --force
    - bin/console assets:install --env=test --no-debug
    - bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json
    - yarn install
    - yarn encore dev

    - php -v
    - php -i | grep -v GITHUB_OAUTH_TOKEN

script:
  - composer validate
  - bin/behat --strict
  - bin/phpunit --stop-on-failure
  - vendor/bin/phplint