enhavo_article_category_index:
    options:
        expose: true
    path: /enhavo/article/category/index
    methods: [GET]
    defaults:
        _controller: enhavo_taxonomy.controller.term::listAction
        _sylius:
            viewer:
                label: article.label.category
                translation_domain: EnhavoArticleBundle
                data_route: enhavo_article_category_data
                batch_route: enhavo_article_category_batch
                open_route: enhavo_article_category_update
                actions:
                    create:
                        type: create
                        route: enhavo_article_category_create

enhavo_article_category_create:
    options:
        expose: true
    path:  /enhavo/article/category/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_taxonomy.controller.term::createAction
        _sylius:
            redirect: enhavo_article_category_update
            form: 'Enhavo\Bundle\ArticleBundle\Form\Type\CategoryType'
            factory:
                method: createNewOnTaxonomy
                arguments:
                    - 'article_category'

enhavo_article_category_update:
    options:
        expose: true
    path:  /enhavo/article/category/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_taxonomy.controller.term::updateAction
        _sylius:
            form: 'Enhavo\Bundle\ArticleBundle\Form\Type\CategoryType'
            viewer:
                actions_secondary:
                    delete:
                        type: delete
                        route: enhavo_article_category_delete

enhavo_article_category_data:
    options:
        expose: true
    path:  /enhavo/article/category/table
    defaults:
        _controller: enhavo_taxonomy.controller.term::listDataAction
        _sylius:
            repository:
                method: findRootsByTaxonomyName
                arguments:
                    - 'article_category'
                    - true
            viewer:
                translation_domain: EnhavoTaxonomyBundle
                width: 12
                children_property: children
                parent_property: parent
                columns:
                    name:
                        type: property
                        width: 12
                        label: term.label.name
                        translation_domain: EnhavoTaxonomyBundle
                        property: name

enhavo_article_category_delete:
    options:
        expose: true
    path: /enhavo/article/category/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_taxonomy.controller.term::deleteAction
        _sylius:
            redirect: enhavo_article_category_index

enhavo_article_category_batch:
    options:
        expose: true
    path: /enhavo/article/category/batch
    methods: [POST]
    defaults:
        _controller: enhavo_taxonomy.controller.term::batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete

enhavo_article_category_auto_complete:
    options:
        expose: true
    path: /enhavo/article/category/auto_complete
    defaults:
        _controller: enhavo_form.controller.auto_complete::searchAction
        _config:
            class: Enhavo\Bundle\TaxonomyBundle\Entity\Term
            repository:
                method: findByTaxonomyTerm
                arguments:
                    - expr:configuration.getSearchTerm()
                    - 'article_category'
                    - expr:configuration.getLimit()
            choice_label: name
