enhavo_media_download:
    pattern:  /media/download/{path}
    defaults:
        _controller: CmfMediaBundle:File:download
        _method: GET

enhavo_media_upload:
    pattern:  /media/file/upload/{editor}
    defaults:
        _controller: CmfMediaBundle:File:upload
        _format: json
        _method: POST