parameters:
    environment: dev
    debug: true
    debug_toolbar: false

    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     enhavo
    database_user:     root
    database_password: root

    mailer_transport:  mail
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
    mailer_delivery_address: ~
    mailer_from: no-reply@enhavo.com
    mailer_name: enhavo
    mailer_to: no-reply@enhavo.com

    secret:            ThisTokenIsNotSoSecretChangeIt

    paypal.express_checkout.username: ~
    paypal.express_checkout.password: ~
    paypal.express_checkout.signature: ~
    paypal.express_checkout.sandbox: true