enhavo_article_admin:
    resource: "@EnhavoArticleBundle/Resources/config/routes/admin/*"
    prefix: /admin

enhavo_article_theme:
    resource: "@EnhavoArticleBundle/Resources/config/routes/theme/*"
    prefix: /

enhavo_article_api:
    resource: "@EnhavoArticleBundle/Resources/config/routes/api/*"
    prefix: /api