enhavo_calendar_appointment_export:
    options:
        expose: true
    path: /calendar/export.ics
    methods: [GET]
    defaults:
        _controller: EnhavoCalendarBundle:Export::export

enhavo_calendar_feed:
    options:
        expose: true
    path: /calendar/feed
    methods: [GET]
    defaults:
        _controller: EnhavoCalendarBundle:Export::feed