Enhavo\Bundle\GridBundle\Model\Column\OneColumnItem:
    type: entity
    table: grid_item_one_column

    manyToOne:
        column:
            cascade: ['persist', 'remove', 'refresh']
            targetEntity: Enhavo\Bundle\GridBundle\Model\GridInterface
            joinColumn:
                onDelete: CASCADE

    lifecycleCallbacks: {  }
