services:
    enhavo_translation.translation.access_control:
        class: Enhavo\Bundle\TranslationBundle\EventListener\AccessControl
        arguments:
            - '@request_stack'
            - '%enhavo_translation.translator.access_control%'
            - '%enhavo_translation.translator.default_access%'

    enhavo_translation.form.access_control:
        class: Enhavo\Bundle\TranslationBundle\EventListener\AccessControl
        arguments:
            - '@request_stack'
            - '%enhavo_translation.form.access_control%'
            - '%enhavo_translation.form.default_access%'

    Enhavo\Bundle\TranslationBundle\EventListener\DoctrineTranslationSubscriber:
        arguments:
            - '@enhavo_translation.translation.access_control'
            - '@Enhavo\Component\Metadata\MetadataRepository[Translation]'
            - '@enhavo_app.locale_resolver'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: doctrine.event_listener, event: preRemove, method: preRemove }
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }
            - { name: doctrine.event_listener, event: postFlush, method: postFlush }

    Enhavo\Bundle\TranslationBundle\Locale\LocalePathResolver:
        arguments:
            - '@request_stack'
            - '@Enhavo\Bundle\TranslationBundle\Locale\LocaleProviderInterface'

    Enhavo\Bundle\TranslationBundle\Locale\ConfigurationLocaleProvider:
        arguments:
            - '%enhavo_translation.locales%'
            - '%enhavo_translation.default_locale%'

    Enhavo\Bundle\TranslationBundle\Locale\LocaleResolver:
        arguments:
            - '@request_stack'
            - '@Enhavo\Bundle\TranslationBundle\Locale\LocaleProviderInterface'
            - '@Enhavo\Bundle\TranslationBundle\Locale\LocaleProviderInterface'

    Enhavo\Bundle\TranslationBundle\Translator\Text\TextTranslator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\EntityResolverInterface'
            - '@Enhavo\Bundle\TranslationBundle\Locale\LocaleProviderInterface'

    Enhavo\Bundle\TranslationBundle\Translator\Route\RouteTranslator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\EntityResolverInterface'
            - '@Enhavo\Bundle\TranslationBundle\Locale\LocaleProviderInterface'

    Enhavo\Bundle\TranslationBundle\Translator\Media\FileTranslator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\EntityResolverInterface'
            - '@Enhavo\Bundle\TranslationBundle\Locale\LocaleProviderInterface'


#    enhavo_translation.preview_listener:
#        class: Enhavo\Bundle\TranslationBundle\EventListener\PreviewListener
#        arguments:
#            - '@enhavo_translation.locale_resolver'
#        tags:
#            - { name: kernel.event_listener, event: enhavo_app.init_preview, method: onInitPreview }
