services:
    enhavo_translation.text.translator:
        class: Enhavo\Bundle\TranslationBundle\Translator\Text\TextTranslator
        arguments:
            - '@enhavo_translation.metadata.repository'
            - '%enhavo_translation.default_locale%'
            - '@enhavo_app.reference.target_class_resolver'
            - '@doctrine.orm.entity_manager'
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_translation.text.access_control:
        class: Enhavo\Bundle\TranslationBundle\Translator\Text\AccessControl
        arguments:
            - '@request_stack'
            - '@enhavo_app.locale_resolver'
            - '%enhavo_translation.translator.access_control%'

    enhavo_translation.event_listener.translation_reference:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineReferenceListener
        arguments:
            - 'Enhavo\Bundle\TranslationBundle\Entity\Translation'
            - 'object'
            - 'class'
            - 'refId'
            - '@enhavo_app.reference.target_class_resolver'
        tags:
            - { name: doctrine.event_subscriber }

    Enhavo\Bundle\TranslationBundle\EventListener\DoctrineTextTranslatorSubscriber:
        class: Enhavo\Bundle\TranslationBundle\EventListener\DoctrineTextTranslatorSubscriber
        arguments:
            - '@enhavo_translation.text.translator'
            - '@enhavo_translation.text.access_control'
            - '@enhavo_translation.metadata.repository'
        tags:
            - { name: doctrine.event_subscriber, connection: default,  priority: 1000 }

    Enhavo\Bundle\TranslationBundle\Locale\LocalePathResolver:
        arguments:
            - '@request_stack'
            - '%enhavo_translation.locales%'
            - '%enhavo_translation.default_locale%'

#    enhavo_translation.strategy.route_translation:
#        class: Enhavo\Bundle\TranslationBundle\Translator\Strategy\RouteTranslationStrategy
#        arguments:
#            - '%enhavo_translation.locales%'
#            - '@enhavo_translation.locale_resolver'
#            - '@doctrine.orm.entity_manager'
#            - '@enhavo_app.route_guesser'
#        calls:
#            - [ setContainer, ['@service_container']]

#    enhavo_translation.strategy.slug_translation:
#        class: Enhavo\Bundle\TranslationBundle\Translator\Strategy\SlugTranslationStrategy
#        arguments:
#            - '%enhavo_translation.locales%'
#            - '@enhavo_translation.locale_resolver'
#            - '@doctrine.orm.entity_manager'
#            - '@enhavo_app.route_guesser'
#        calls:
#            - [ setContainer, ['@service_container']]

#    enhavo_translation.preview_listener:
#        class: Enhavo\Bundle\TranslationBundle\EventListener\PreviewListener
#        arguments:
#            - '@enhavo_translation.locale_resolver'
#        tags:
#            - { name: kernel.event_listener, event: enhavo_app.init_preview, method: onInitPreview }

#    enhavo_translation.slug_translator:
#        class: Enhavo\Bundle\TranslationBundle\Translator\SlugTranslator
#        arguments:
#            - '@doctrine.orm.entity_manager'
#            - '@enhavo_translation.locale_resolver'

#    enhavo_translation.translation_route_manager:
#        class: Enhavo\Bundle\TranslationBundle\Route\TranslationRouteManager
#        arguments:
#            - '@enhavo_app.route_manager'
#            - '@doctrine.orm.entity_manager'