enhavo_category_collection_update:
    options:
        expose: true
    path: /enhavo/category/collection/update/{collection}
    methods: [GET, POST]
    defaults:
        _controller: enhavo_category.controller.collection:updateAction
        _sylius:
            repository:
                method: findCollectionOrCreate
                arguments: $collection
            template: EnhavoAppBundle:Resource:update-small.html.twig
            viewer:
                translationDomain: EnhavoCategoryBundle
                form:
                    action: ~
                    delete: ~
                buttons:
                    delete:
                        display: false
                    save:
                        route: enhavo_category_collection_update
                        routeParameters:
                            collection: $collection
                tabs:
                    main:
                        label: category.label.categories
                        template: EnhavoCategoryBundle:Tab:collection.html.twig