cmf_routing:
# Use this settings if you want to provide some dynamic routing features
#    dynamic:
#        controllers_by_class:
#            Enhavo\Bundle\ArticleBundle\Entity\Article: EnhavoAppBundle:App:show
#            Enhavo\Bundle\PageBundle\Entity\Page: EnhavoAppBundle:App:show

enhavo_app:
    permission_check: false
    dynamic_routing: false
    stylesheets:
      - '@EnhavoDownloadBundle/Resources/public/css/style.css'
    javascripts:

    viewer:
#        layout: 'EnhavoAppBundle::base.html.twig'
        app: Enhavo\Bundle\AppBundle\Viewer\AppViewer
    menu:
        dashboard:
            label: dashboard.label.dashboard
            translationDomain: EnhavoDashboardBundle
            route: enhavo_dashboard_index
            role: ROLE_ESPERANTO_USER_USER_INDEX
        user:
            label: user.label.user
            translationDomain: EnhavoUserBundle
            route: enhavo_user_user_index
            role: ROLE_ESPERANTO_USER_USER_INDEX
        group:
            label: group.label.group
            translationDomain: EnhavoUserBundle
            route: enhavo_user_group_index
            role: ROLE_ESPERANTO_USER_GROUP_INDEX
        article:
            label: article.label.article
            translationDomain: EnhavoArticleBundle
            route: enhavo_article_article_index
            role: ROLE_ESPERANTO_NEWS_NEWS_INDEX
        page:
            label: page.label.page
            translationDomain: EnhavoPageBundle
            route: enhavo_page_page_index
            role: ROLE_ESPERANTO_PAGE_PAGE_INDEX
        category:
            label: category.label.categories
            translationDomain: EnhavoCategoryBundle
            route: enhavo_category_category_index
            role: ROLE_ESPERANTO_CATEGORY_CATEGORY_INDEX
        download:
            label: download.label.download
            translationDomain: EnhavoDownloadBundle
            route: enhavo_download_download_index
            role: ROLE_ESPERANTO_DOWNLOAD_DOWNLOAD_INDEX
        slider:
            label: slider.label.slider
            translationDomain: EnhavoSliderBundle
            route: enhavo_slider_slide_index
            role: ROLE_ESPERANTO_SLIDER_SLIDER_INDEX
        newsletter:
            label: newsletter.label.newsletter
            translationDomain: EnhavoNewsletterBundle
            route: enhavo_newsletter_newsletter_index
            role: ROLE_ESPERANTO_NEWSLETTER_NEWSLETTER_INDEX
        calendar:
            label: label.calendar
            translationDomain: EnhavoCalendarBundle
            route: enhavo_calendar_appointment_index
            role: ROLE_ESPERANTO_CALENDAR_CALENDAR_INDEX

enhavo_grid:
    render:
        sets:
            default:
#                picture: enhavoProjectBundle:ItemType:picture.html.twig

    items:
        picture:
            model: Enhavo\Bundle\GridBundle\Entity\Picture
            form: Enhavo\Bundle\GridBundle\Form\Type\PictureType
            repository: EnhavoGridBundle:Picture
            template: EnhavoGridBundle:Item:picture.html.twig
            label: picture.label.picture
            translationDomain: EnhavoGridBundle
        picture_picture:
            model: Enhavo\Bundle\GridBundle\Entity\PicturePicture
            form: Enhavo\Bundle\GridBundle\Form\Type\PicturePictureType
            repository: EnhavoGridBundle:PicturePicture
            template: EnhavoGridBundle:Item:picture_picture.html.twig
            label: picturePicture.label.picturePicture
            translationDomain: EnhavoGridBundle
        gallery:
            model: Enhavo\Bundle\GridBundle\Entity\Gallery
            form: Enhavo\Bundle\GridBundle\Form\Type\GalleryType
            repository: EnhavoGridBundle:Gallery
            template: EnhavoGridBundle:Item:gallery.html.twig
            label: gallery.label.gallery
            translationDomain: EnhavoGridBundle
        text:
            model: Enhavo\Bundle\GridBundle\Entity\Text
            form: Enhavo\Bundle\GridBundle\Form\Type\TextType
            repository: EnhavoGridBundle:Text
            template: EnhavoGridBundle:Item:text.html.twig
            label: text.label.text
            translationDomain: EnhavoGridBundle
        text_picture:
            model: Enhavo\Bundle\GridBundle\Entity\TextPicture
            form: Enhavo\Bundle\GridBundle\Form\Type\TextPictureType
            repository: EnhavoGridBundle:TextPicture
            template: EnhavoGridBundle:Item:text_picture.html.twig
            label: textPicture.label.textPicture
            translationDomain: EnhavoGridBundle
        text_text:
            model: Enhavo\Bundle\GridBundle\Entity\TextText
            form: Enhavo\Bundle\GridBundle\Form\Type\TextTextType
            repository: EnhavoGridBundle:TextText
            template: EnhavoGridBundle:Item:text_text.html.twig
            label: textText.label.textText
            translationDomain: EnhavoGridBundle
        cite_text:
            model: Enhavo\Bundle\GridBundle\Entity\CiteText
            form: Enhavo\Bundle\GridBundle\Form\Type\CiteTextType
            repository: EnhavoGridBundle:CiteText
            template: EnhavoGridBundle:Item:cite_text.html.twig
            label: citeText.label.citeText
            translationDomain: EnhavoGridBundle
        download:
            model: Enhavo\Bundle\DownloadBundle\Entity\DownloadItem
            form: Enhavo\Bundle\DownloadBundle\Form\Type\DownloadItemType
            repository: EnhavoDownloadBundle:DownloadItem
            template: EnhavoDownloadBundle:Item:download.html.twig
            label: download.label.download
            translationDomain: EnhavoGridBundle

enhavo_page:
    dynamic_routing: false
    classes:
        page:
            model: Enhavo\Bundle\PageBundle\Entity\Page
            form: Enhavo\Bundle\PageBundle\Form\Type\PageType

enhavo_article:
    dynamic_routing: false
    classes:
         article:
            model: Enhavo\Bundle\ArticleBundle\Entity\Article
            form: Enhavo\Bundle\ArticleBundle\Form\Type\ArticleType
            repository: Enhavo\Bundle\ArticleBundle\Repository\ArticleRepository

enhavo_category:
    default_collection: default

enhavo_contact:
    contact:
        model: Enhavo\Bundle\ContactBundle\Model\Contact
        form: Enhavo\Bundle\ContactBundle\Form\Type\ContactFormType
        template:
            form: EnhavoContactBundle:Contact:form.html.twig
            recipient: EnhavoContactBundle:Contact:recipient.html.twig
            sender: EnhavoContactBundle:Contact:sender.html.twig
        recipient: %contact_form_recipient%
        from: %emails_send_from%
        subject: Kontaktformular
        send_to_sender: true