parameters:
    locale: en

enhavo_app:
    menu:
        dashboard:
            type: dashboard
        user:
            type: user
        article:
            type: article
        page:
            type: page
        category:
            type: category
        download:
            type: download
        slider:
            type: slider
        newsletter:
            type: newsletter
        calendar:
            type: calendar
        shop:
            type: shop
        setting:
            type: setting
        navigation:
            type: navigation
        translation_strings:
            type: translation
        redirect:
            type: redirect
        magazine:
            type: base
            route: enhavo_project_magazine_index
            icon: open-book
            label: Magazine

enhavo_grid:
    items:
        picture:
            type: picture
        picture_picture:
            type: picture_picture
        three_picture:
            type: three_picture
        gallery:
            type: gallery
        text:
            type: text
        text_picture:
            type: text_picture
        text_text:
            type: text_text
        cite_text:
            type: cite_text
        download:
            type: download
        video:
            type: video