#
# theme
#
enhavo_theme_hompage:
    resource: "@EnhavoThemeBundle/Resources/config/routing/homepage.yml"
    prefix:   /

enhavo_theme_download:
    resource: "@EnhavoThemeBundle/Resources/config/routing/download.yml"
    prefix:   /

enhavo_theme_article:
    resource: "@EnhavoThemeBundle/Resources/config/routing/article.yml"
    prefix:   /

#
# enhavo
#
enhavo_shop:
    resource: "@EnhavoShopBundle/Resources/config/routing/shop.yml"
    prefix:   /

enhavo_contact:
    resource: "@EnhavoContactBundle/Resources/config/routing.yml"
    prefix:   /

enhavo_search:
    resource: "@EnhavoSearchBundle/Resources/config/routing.yml"
    prefix:   /

enhavo_media:
    resource: "@EnhavoMediaBundle/Resources/config/routing.yml"
    prefix:   /

enhavo_sitemap:
    resource: "@EnhavoContentBundle/Resources/config/routing/sitemap.yml"
    prefix:   /

enhavo_newsletter_subscriber:
    resource: "@EnhavoNewsletterBundle/Resources/config/routing/subscriber.yml"
    prefix: /

enhavo_user_security:
    resource: "@EnhavoUserBundle/Resources/config/routing/security.yml"
    prefix:   /admin

enhavo_admin:
    resource: "@EnhavoAppBundle/Resources/config/routing/admin.yml"
    prefix: /admin

enhavo_dashboard:
    resource: "@EnhavoDashboardBundle/Resources/config/routing.yml"
    prefix:   /admin

enhavo_article:
    resource: "@EnhavoArticleBundle/Resources/config/routing/article.yml"
    prefix: /admin

enhavo_page:
    resource: "@EnhavoPageBundle/Resources/config/routing/page.yml"
    prefix: /admin

enhavo_download:
    resource: "@EnhavoDownloadBundle/Resources/config/routing/download.yml"
    prefix: /admin

enhavo_slide:
    resource: "@EnhavoSliderBundle/Resources/config/routing/slide.yml"
    prefix: /admin

enhavo_user:
    resource: "@EnhavoUserBundle/Resources/config/routing/user.yml"
    prefix: /admin

enhavo_group:
    resource: "@EnhavoUserBundle/Resources/config/routing/group.yml"
    prefix: /admin

enhavo_grid:
    resource: "@EnhavoGridBundle/Resources/config/routing/routing.yml"
    prefix: /admin

enhavo_newsletter_newsletter:
    resource: "@EnhavoNewsletterBundle/Resources/config/routing/newsletter.yml"
    prefix: /admin

enhavo_category_category:
    resource: "@EnhavoCategoryBundle/Resources/config/routing/category.yml"
    prefix: /admin

enhavo_category_collection:
    resource: "@EnhavoCategoryBundle/Resources/config/routing/collection.yml"
    prefix: /admin

enhavo_workflow:
    resource: "@EnhavoWorkflowBundle/Resources/config/routing/workflow.yml"
    prefix: /admin

enhavo_calendar:
    resource: "@EnhavoCalendarBundle/Resources/config/routing/appointment.yml"
    prefix: /admin

#
# 3rd Party
#
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

sylius_flow:
    resource: "@SyliusFlowBundle/Resources/config/routing.yml"
    prefix: /