enhavo_user_theme_login:
    options:
        expose: true
    path: /login
    methods: [GET, POST]
    defaults:
        _format: html
        _config: theme
        _endpoint:
            type: user_login_app
            translations: EnhavoUserBundle
            template: /{{ area }}/user/login.html.twig
        _vue:
            component: user-login
            groups: theme

enhavo_user_theme_logout:
    options:
        expose: true
    path: /logout
    methods: [GET, POST]
    defaults:
        _config: admin
        _endpoint:
            type: user_login_app
            template: /{{ area }}/user/login.html.twig

