enhavo_user_theme_login:
    options:
        expose: true
    path: /login
    methods: [GET, POST]
    defaults:
        _format: html
        _config: theme
        _endpoint:
            type: view

enhavo_user_theme_logout:
    options:
        expose: true
    path: /logout
    methods: [GET, POST]
    defaults:
        _config: admin
        _endpoint:
            type: view
