enhavo_user_theme_security_login:
    options:
        expose: true
    path: /login
    methods: [GET]
    controller: Enhavo\Bundle\UserBundle\Controller\SecurityController::loginAction
    defaults:
        _config: theme

enhavo_user_theme_security_login_check:
    options:
        expose: true
    path: /login/check
    methods: [POST]
    controller: Enhavo\Bundle\UserBundle\Controller\SecurityController::checkAction

enhavo_user_theme_security_logout:
    options:
        expose: true
    path: /logout
    methods: [GET, POST]
    controller: Enhavo\Bundle\UserBundle\Controller\SecurityController::logoutAction
