Enhavo\Bundle\ArticleBundle\Entity\Article:
    priority: 5
    index: false
    properties:
        title:
            - Plain:
                weight: 10
                type: title

        teaser:
            - Plain:
                weight: 8
                type: teaser

        content:
            - Model

        tag:
            - Collection:
                type: text