services:
    Enhavo\Bundle\NavigationBundle\Menu\NavigationMenu:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: navigation }

    Enhavo\Bundle\NavigationBundle\Form\Type\NavigationType:
        arguments:
            - '%enhavo_navigation.model.navigation.class%'
            - [default]
        tags:
            - { name: form.type }

    enhavo_navigation.extend_listener.navigation:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NavigationBundle\Entity\Navigation
            - '%enhavo_navigation.model.navigation.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_navigation.extend_listener.node:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NavigationBundle\Entity\Node
            - '%enhavo_navigation.model.node.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_navigation.event_listener.node_reference:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineReferenceListener
        arguments:
          - 'Enhavo\Bundle\NavigationBundle\Entity\Node'
          - 'content'
          - 'contentClass'
          - 'contentId'
          - '@enhavo_app.reference.target_class_resolver'
        tags:
            - { name: doctrine.event_subscriber }

    enhavo_navigation.item_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'NavigationItem'

    enhavo_navigation.resolver.node_resolver:
        class: Enhavo\Bundle\NavigationBundle\Resolver\NodeResolver
        public: true
        calls:
            - ['setContainer', ['@service_container']]
        arguments:
            - '@form.factory'
            - '@enhavo_navigation.item.item_manager'

    enhavo_navigation.form.node_type:
        class: Enhavo\Bundle\NavigationBundle\Form\Type\NodeType
        arguments:
            - '%enhavo_navigation.model.node.class%'
        tags:
            - { name: form.type, alias: 'enhavo_navigation_node' }

    enhavo_navigation.form.nodes_type:
        class: Enhavo\Bundle\NavigationBundle\Form\Type\NodesType
        arguments:
            - '%enhavo_navigation.model.node.class%'
        tags:
            - { name: form.type, alias: 'enhavo_navigation_nodes' }

    Enhavo\Bundle\NavigationBundle\Item\Configuration\LinkConfiguration:
        public: true
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'link' }

    Enhavo\Bundle\NavigationBundle\Item\Configuration\SubmenuConfiguration:
        public: true
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'submenu' }

    Enhavo\Bundle\NavigationBundle\Item\Configuration\NodeConfiguration:
        public: true
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'node' }

    Enhavo\Bundle\NavigationBundle\Widget\NavigationWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: 'navigation' }

    enhavo_navigation.node.manager:
        class: Enhavo\Bundle\NavigationBundle\Node\NodeManager
        calls:
            - [setContainer, ['@service_container']]

    enhavo_navigation.voter_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'NavigationVoter'

    enhavo_navigation.voter.link:
        class: Enhavo\Bundle\NavigationBundle\Node\Voter\LinkVoter
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_navigation.voter, alias: 'link' }

    enhavo_navigation.voter.link_hierarchy:
        class: Enhavo\Bundle\NavigationBundle\Node\Voter\LinkHierarchyVoter
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_navigation.voter, alias: 'link_hierarchy' }

    enhavo_navigation.voter.node_hierarchy:
        class: Enhavo\Bundle\NavigationBundle\Node\Voter\NodeHierarchyVoter
        arguments:
            - '@enhavo_navigation.node.manager'
        tags:
            - { name: enhavo_navigation.voter, alias: 'node_hierarchy' }

    enhavo_navigation.twig.extension:
        class: Enhavo\Bundle\NavigationBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }
        arguments:
            - '@enhavo_navigation.node.manager'
            - '@enhavo_navigation.renderer.node_renderer'

    enhavo_navigation.renderer.node_renderer:
        class: Enhavo\Bundle\NavigationBundle\Renderer\NodeRenderer
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            - '@enhavo_navigation.item.item_manager'
            - '%enhavo_navigation.render.sets%'

    enhavo_navigation.item.item_manager:
        class: Enhavo\Bundle\NavigationBundle\Item\ItemManager
        arguments:
            - '@enhavo_navigation.item_collector'
            - '%enhavo_navigation.items%'




