services:
    Enhavo\Bundle\NavigationBundle\Menu\NavigationMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: navigation }

    Enhavo\Bundle\NavigationBundle\Form\Type\NavigationType:
        arguments:
            - '%enhavo_navigation.model.navigation.class%'
            - [default]
        tags:
            - { name: form.type }

    enhavo_navigation.item_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'NavigationItem'

    enhavo_navigation.resolver.node_resolver:
        class: Enhavo\Bundle\NavigationBundle\Resolver\NodeResolver
        public: true
        calls:
            - ['setContainer', ['@service_container']]
        arguments:
            - '@form.factory'
            - '@enhavo_navigation.item.item_manager'

    enhavo_navigation.form.node_type:
        class: Enhavo\Bundle\NavigationBundle\Form\Type\NodeType
        arguments:
            - '%enhavo_navigation.model.node.class%'
        tags:
            - { name: form.type, alias: 'enhavo_navigation_node' }

    enhavo_navigation.form.nodes_type:
        class: Enhavo\Bundle\NavigationBundle\Form\Type\NodesType
        arguments:
            - '%enhavo_navigation.model.node.class%'
        tags:
            - { name: form.type, alias: 'enhavo_navigation_nodes' }

    Enhavo\Bundle\NavigationBundle\Item\Configuration\LinkConfiguration:
        public: true
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'link' }

    Enhavo\Bundle\NavigationBundle\Item\Configuration\SubmenuConfiguration:
        public: true
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'submenu' }

    Enhavo\Bundle\NavigationBundle\Item\Configuration\NodeConfiguration:
        public: true
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'node' }

    Enhavo\Bundle\NavigationBundle\Widget\NavigationWidgetType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: 'navigation' }

    enhavo_navigation.node.manager:
        class: Enhavo\Bundle\NavigationBundle\Node\NodeManager
        arguments:
            - '@enhavo_navigation.voter_collector'
        calls:
            - [setContainer, ['@service_container']]

    enhavo_navigation.voter_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'NavigationVoter'

    Enhavo\Bundle\NavigationBundle\Node\Voter\LinkVoter:
        public: true
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_navigation.voter, alias: 'link' }

    Enhavo\Bundle\NavigationBundle\Node\Voter\LinkHierarchyVoter:
        public: true
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_navigation.voter, alias: 'link_hierarchy' }

    Enhavo\Bundle\NavigationBundle\Node\Voter\NodeHierarchyVoter:
        public: true
        arguments:
            - '@enhavo_navigation.node.manager'
        tags:
            - { name: enhavo_navigation.voter, alias: 'node_hierarchy' }

    enhavo_navigation.twig.extension:
        class: Enhavo\Bundle\NavigationBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }
        arguments:
            - '@enhavo_navigation.node.manager'
            - '@enhavo_navigation.renderer.node_renderer'

    enhavo_navigation.renderer.node_renderer:
        class: Enhavo\Bundle\NavigationBundle\Renderer\NodeRenderer
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            - '@enhavo_navigation.item.item_manager'
            - '%enhavo_navigation.render.sets%'

    enhavo_navigation.item.item_manager:
        class: Enhavo\Bundle\NavigationBundle\Item\ItemManager
        arguments:
            - '@enhavo_navigation.item_collector'
            - '%enhavo_navigation.items%'
