services:
    Enhavo\Bundle\NavigationBundle\Menu\NavigationMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: navigation }

    Enhavo\Bundle\NavigationBundle\Form\Type\NavigationType:
        arguments:
            - '%enhavo_navigation.model.navigation.class%'
            - [default]
        tags:
            - { name: form.type }

    Enhavo\Bundle\NavigationBundle\Form\Type\NodeType:
        arguments:
            - '%enhavo_navigation.model.node.class%'
        tags:
            - { name: form.type, alias: 'enhavo_navigation_node' }

    Enhavo\Bundle\NavigationBundle\Form\Type\NodeCollectionType:
        arguments:
            - '%enhavo_navigation.model.node.class%'
            - '%enhavo_navigation.form.node.class%'
            - '@Enhavo\Bundle\NavigationBundle\NavItem\NavItemManager'
        tags:
            - { name: form.type, alias: 'enhavo_navigation_nodes' }

    Enhavo\Bundle\NavigationBundle\NavItem\Type\NavItemType:
        tags:
            - { name: enhavo_navigation.nav_item }

    Enhavo\Bundle\NavigationBundle\NavItem\Type\LinkNavItemType:
        tags:
            - { name: enhavo_navigation.nav_item }

    Enhavo\Bundle\NavigationBundle\NavItem\Type\SubmenuNavItemType:
        tags:
            - { name: enhavo_navigation.nav_item }

    Enhavo\Bundle\NavigationBundle\NavItem\Type\ContentNavItemType:
        tags:
            - { name: enhavo_navigation.nav_item }

    Enhavo\Bundle\NavigationBundle\NavItem\NavItemManager:
        arguments:
            - '@Enhavo\Component\Type\FactoryInterface[NavItem]'
            - '%enhavo_navigation.nav_items%'
        calls:
            - [setContainer, [ '@service_container' ] ]

    Enhavo\Bundle\NavigationBundle\Widget\NavigationWidgetType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: 'navigation' }

    Enhavo\Bundle\NavigationBundle\Navigation\NavigationManager:

    Enhavo\Bundle\NavigationBundle\Voter\LinkVoter:
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_navigation.voter }

    Enhavo\Bundle\NavigationBundle\Voter\LinkHierarchyVoter:
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_navigation.voter }

    Enhavo\Bundle\NavigationBundle\Voter\NodeHierarchyVoter:
        arguments:
            - '@Enhavo\Bundle\NavigationBundle\Navigation\NavigationManager'
        tags:
            - { name: enhavo_navigation.voter }

    Enhavo\Bundle\NavigationBundle\Twig\TwigExtension:
        tags:
            - { name: twig.extension }
        arguments:
            - '@Enhavo\Bundle\NavigationBundle\Navigation\NavigationManager'
            - '@Enhavo\Bundle\NavigationBundle\Renderer\NodeRenderer'

    Enhavo\Bundle\NavigationBundle\Renderer\NodeRenderer:
        arguments:
            - '@Enhavo\Bundle\NavigationBundle\NavItem\NavItemManager'
            - '%enhavo_navigation.render.sets%'
        calls:
            - [setContainer, ['@service_container']]
            - [setTwig, ['@twig']]
            - [setTemplateResolver, ['@Enhavo\Bundle\AppBundle\Template\TemplateResolverInterface']]
