services:
    enhavo_navigation.menu.navigation:
        class: Enhavo\Bundle\NavigationBundle\Menu\NavigationMenu
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: navigation }

    enhavo_navigation.extend_listener.navigation:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NavigationBundle\Entity\Navigation
            - '%enhavo_navigation.model.navigation.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_navigation.extend_listener.node:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NavigationBundle\Entity\Node
            - '%enhavo_navigation.model.node.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_navigation.event_listener.node_reference:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineReferenceListener
        arguments:
          - 'Enhavo\Bundle\NavigationBundle\Entity\Node'
          - 'content'
          - 'contentClass'
          - 'contentId'
          - '@enhavo_app.reference.target_class_resolver'
        tags:
            - { name: doctrine.event_subscriber }

    enhavo_navigation.item_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'NavigationItem'

    enhavo_navigation.resolver.node_resolver:
        class: Enhavo\Bundle\NavigationBundle\Resolver\NodeResolver
        calls:
            - ['setContainer', ['@service_container']]
        arguments:
            - '@form.factory'
            - '@enhavo_navigation.item_collector'
            - '%enhavo_navigation.items%'

    enhavo_navigation.form.node_type:
        class: Enhavo\Bundle\NavigationBundle\Form\Type\NodeType
        arguments:
            - '%enhavo_navigation.model.node.class%'
        tags:
            - { name: form.type, alias: 'enhavo_navigation_node' }

    enhavo_navigation.form.nodes_type:
        class: Enhavo\Bundle\NavigationBundle\Form\Type\NodesType
        arguments:
            - '%enhavo_navigation.model.node.class%'
        tags:
            - { name: form.type, alias: 'enhavo_navigation_nodes' }

    enhavo_navigation.item.configuration.link_configuration:
        class: Enhavo\Bundle\NavigationBundle\Item\Configuration\LinkConfiguration
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'link' }

    enhavo_navigation.item.configuration.submenu_configuration:
        class: Enhavo\Bundle\NavigationBundle\Item\Configuration\SubmenuConfiguration
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'submenu' }

    enhavo_navigation.item.configuration.node_configuration:
        class: Enhavo\Bundle\NavigationBundle\Item\Configuration\NodeConfiguration
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'node' }

    enhavo_navigation.widget.navigation:
        class: Enhavo\Bundle\NavigationBundle\Widget\NavigationWidget
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.theme_widget, alias: 'navigation' }