doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\GridBundle\Model\GridInterface: Enhavo\Bundle\GridBundle\Entity\Grid
            Enhavo\Bundle\GridBundle\Model\ItemInterface: Enhavo\Bundle\GridBundle\Entity\Item

enhavo_media:
    formats:
        enhavoGridFull:
            type: image
            width: 960

enhavo_app:
    form_themes:
        - 'EnhavoGridBundle:Form:fields.html.twig'
