cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        route_provider_service_id: enhavo_app.route_provider

doctrine:
    dbal:
        mapping_types:
            enum: string
    orm:
        resolve_target_entities:
            Enhavo\Bundle\RoutingBundle\Model\RouteInterface: Enhavo\Bundle\RoutingBundle\Entity\Route

enhavo_doctrine_extension:
    metadata:
        Enhavo\Bundle\RoutingBundle\Entity\Route:
            reference:
                content:
                    idField: contentId
                    nameField: contentClass

enhavo_routing:
    classes:
        Enhavo\Bundle\RoutingBundle\Entity\Route:
            router:
                default:
                    type: route

enhavo_app:
    form_themes:
        - '@EnhavoRouting/admin/form/route/fields.html.twig'
