enhavo_user_change_password_change:
    options:
        expose: true
    path: /enhavo/user/change-password
    methods: [ GET, POST ]
    controller: enhavo_user.controller.user:changePasswordAction
    defaults:
        _config: admin
        _sylius:
            form: Enhavo\Bundle\UserBundle\Form\Type\ChangePasswordType
            viewer:
                label: 'change_password.label.edit'
                translation_domain: EnhavoUserBundle
