parameters:

services:
    enhavo_page_page:
        class: '%enhavo_page.form.type.page.class%'
        arguments:
            - '%enhavo_page.model.page.class%'
            - '%enhavo_page.routing.page.strategy%'
            - '%enhavo_page.routing.page.route%'
        tags:
            - { name: form.type }

    enhavo_page.form.type.navigation_page_configuation:
        class: Enhavo\Bundle\PageBundle\Form\Type\NavigationPageConfigurationType
        tags:
            - { name: form.type }

    enhavo_page.form.type.page_choice:
        class: Enhavo\Bundle\PageBundle\Form\Type\PageChoiceType
        arguments:
            - '%enhavo_page.model.page.class%'
        tags:
            - { name: form.type, alias: 'enhavo_page_page_choice' }

    enhavo_page.widget.page:
        class: Enhavo\Bundle\PageBundle\Widget\PageWidget
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.theme_widget, alias: page }

    enhavo_page.extend_listener.page:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\PageBundle\Entity\Page
            - '%enhavo_page.model.page.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_page.twig.page_path_extension:
        class: Enhavo\Bundle\PageBundle\Twig\PagePathExtension
        arguments:
            - '@enhavo_page.repository.page'
            - '@router'
        tags:
            - { name: twig.extension }

    enhavo_page.menu.page:
        class: Enhavo\Bundle\PageBundle\Menu\PageMenu
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: page }

    enhavo_page.factory.page:
        class: '%enhavo_page.factory.page.class%'
        arguments:
            - '%enhavo_page.model.page.class%'
            - '@enhavo_grid.factory.grid'

    enhavo_page.navigation.page_configuration:
        class: Enhavo\Bundle\PageBundle\Navigation\PageConfiguration
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo_navigation.item, alias: 'page' }

    enhavo_page.navigation.page_voter:
        class: Enhavo\Bundle\PageBundle\Navigation\Voter\PageVoter
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_navigation.voter, alias: 'page' }

    enhavo_page.navigation.page_hierarchy_voter:
        class: Enhavo\Bundle\PageBundle\Navigation\Voter\PageHierarchyVoter
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_navigation.voter, alias: 'page_hierarchy' }