enhavo_newsletter_subscribe_activate:
    path: /newsletter/activate/{token}/{type}
    options:
        expose: true
    controller: Enhavo\Bundle\NewsletterBundle\Controller\SubscriptionController::activateAction

enhavo_newsletter_subscribe_add:
    path: /newsletter/add/{type}
    options:
        expose: true
    controller: Enhavo\Bundle\NewsletterBundle\Controller\SubscriptionController::addAction
    methods: [POST]

enhavo_newsletter_subscriber_unsubscribe:
    path: /newsletter/unsubscribe/{token}/{type}
    options:
        expose: true
    controller: Enhavo\Bundle\NewsletterBundle\Controller\SubscriptionController::unsubscribeAction
