enhavo_newsletter_tracking_open:
    path: /newsletter/tracking/{token}/open
    methods: [GET]
    defaults:
        _controller: Enhavo\Bundle\NewsletterBundle\Controller\TrackingController::openAction
