enhavo_download_download_index:
    options:
        expose: true
    path: /enhavo/download/download/index
    methods: [GET]
    defaults:
        _controller: enhavo_download.controller.download:indexAction
        _sylius:
            template: EnhavoAppBundle:Resource:index.html.twig
        _viewer:
            title: download.label.download
            translationDomain: EnhavoDownloadBundle

enhavo_download_download_create:
    options:
        expose: true
    path: /enhavo/download/download/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_download.controller.download:createAction
        _sylius:
            template: EnhavoAppBundle:Resource:create.html.twig
        _viewer:
            translationDomain: EnhavoDownloadBundle

enhavo_download_download_update:
    options:
        expose: true
    path: /enhavo/download/download/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_download.controller.download:updateAction
        _sylius:
            template: EnhavoAppBundle:Resource:update.html.twig
        _viewer:
            translationDomain: EnhavoDownloadBundle

enhavo_download_download_table:
    options:
        expose: true
    path: /enhavo/download/download/table/{page}
    methods: [GET]
    defaults:
        page: 1
        _controller: enhavo_download.controller.download:tableAction
        _sylius:
            template: EnhavoAppBundle:Resource:table.html.twig
        _viewer:
            translationDomain: EnhavoDownloadBundle
            table:
                columns:
                    id:
                        label: download.label.id
                        property: id
                    title:
                        label: download.label.title
                        property: title
                        width: 8

enhavo_download_download_delete:
    options:
        expose: true
    path: /enhavo/download/download/delete/{id}
    methods: [DELETE]
    defaults:
        _controller: enhavo_download.controller.download:deleteAction

enhavo_download_download_batch:
    options:
        expose: true
    path: /enhavo/download/download/batch
    methods: [POST]
    defaults:
        _controller: enhavo_download.controller.download:batchAction
