sylius_product_index:
    options:
        expose: true
    path: /enhavo/shop/product/index
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            viewer:

sylius_product_create:
    options:
        expose: true
    path: /enhavo/shop/product/create
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            redirect: sylius_product_update
            viewer:

sylius_product_update:
    options:
        expose: true
    path: /enhavo/shop/product/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            viewer:

sylius_product_table:
    options:
        expose: true
    path: /enhavo/shop/product/table
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product:tableAction
        _sylius:
            viewer:
                columns:
                    id:
                        property: id
                        width: 12
                        label: id
                        type: property

sylius_product_delete:
    options:
        expose: true
    path: /enhavo/shop/product/delete/{id}
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:deleteAction

sylius_product_batch:
    options:
        expose: true
    path: /enhavo/shop/product/batch
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete

sylius_product_preview:
    options:
        expose: true
    path: /enhavo/shop/product/preview
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:previewAction
        _sylius:
            viewer:

sylius_product_resource_preview:
    options:
        expose: true
    path: /enhavo/shop/product/resource/preview
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:previewResourceAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_article.controller.article:showResourceAction

