services:
    enhavo_routing.auto_generator:
        class: Enhavo\Bundle\RoutingBundle\AutoGenerator\AutoGenerator
        arguments:
            - '@enhavo_routing.auto_generator.route_generator_collector'
            - '@Enhavo\Component\Metadata\MetadataRepository[Routing]'

    enhavo_routing.auto_generator.route_generator_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'AutoGenerator'

    Enhavo\Bundle\RoutingBundle\AutoGenerator\Generator\PrefixGenerator:
        public: true
        arguments:
            - '@enhavo_routing.repository.route'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.generator', alias: 'prefix' }

    Enhavo\Bundle\RoutingBundle\AutoGenerator\Generator\GuessPrefixGenerator:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.generator', alias: 'guess' }

    Enhavo\Bundle\RoutingBundle\AutoGenerator\Generator\SlugGenerator:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.generator', alias: 'slug' }

    Enhavo\Bundle\RoutingBundle\AutoGenerator\Generator\RouteNameGenerator:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.generator', alias: 'route_name' }

    Enhavo\Bundle\RoutingBundle\AutoGenerator\Generator\HierarchyPrefixGenerator:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.generator', alias: 'hierarchy_prefix' }