services:
    enhavo_routing.router:
        class: Enhavo\Bundle\RoutingBundle\Router\Router
        arguments:
            - '@enhavo_routing.router.strategy_collector'
            - '@enhavo_routing.metadata.repository'

    enhavo_routing.router.strategy_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'RouterStrategy'

    Enhavo\Bundle\RoutingBundle\Router\Strategy\IdStrategy:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.strategy', alias: 'id' }

    Enhavo\Bundle\RoutingBundle\Router\Strategy\SlugStrategy:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.strategy', alias: 'slug' }

    Enhavo\Bundle\RoutingBundle\Router\Strategy\SlugIdStrategy:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.strategy', alias: 'slug_id' }

    Enhavo\Bundle\RoutingBundle\Router\Strategy\RouteStrategy:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: 'enhavo_route.strategy', alias: 'route' }