services:
    enhavo_grid.context.builder:
        class: Enhavo\Bundle\GridBundle\Context\ContextBuilder

    enhavo_grid.form.items:
        class: Enhavo\Bundle\GridBundle\Form\Type\ItemsType
        arguments:
            - Enhavo\Bundle\GridBundle\Entity\Item
        tags:
            - { name: form.type, alias: enhavo_grid_items }

    enhavo_grid.twig.grid_extension:
        class: Enhavo\Bundle\GridBundle\Twig\GridExtension
        arguments:
            - '@enhavo_grid.renderer.grid_renderer'
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: twig.extension }

    enhavo_grid.renderer.grid_renderer:
        class: Enhavo\Bundle\GridBundle\Renderer\GridRenderer
        arguments:
            - '@enhavo_grid.resolver.item_resolver'
            - '@enhavo_grid.context.builder'
            - '%enhavo_grid.render.sets%'
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_grid.resolver.item_resolver:
        public: true
        class: Enhavo\Bundle\GridBundle\Resolver\ItemResolver
        calls:
            - ['setContainer', ['@service_container']]
        arguments:
            - '@form.factory'
            - '@enhavo_grid.factory.item_type'
            - '@enhavo_grid.item.manager'

    enhavo_grid.item_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'GridItem'

    validator.video_url_validator:
        class:  Enhavo\Bundle\GridBundle\Validator\Constraints\VideoUrlValidator
        tags:
            - { name: validator.constraint_validator, alias: video_url }

    enhavo_grid.event_listener.item_reference:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineReferenceListener
        arguments:
          - 'Enhavo\Bundle\GridBundle\Entity\Item'
          - 'itemType'
          - 'itemTypeClass'
          - 'itemTypeId'
          - '@enhavo_app.reference.target_class_resolver'
        tags:
            - { name: doctrine.event_subscriber }

    enhavo_grid.item.manager:
        class: Enhavo\Bundle\GridBundle\Item\ItemManager
        arguments:
            - '@enhavo_grid.item_collector'
            - '%enhavo_grid.items%'

    Enhavo\Bundle\GridBundle\Maker\MakeGridItem:
        arguments:
            - '@kernel'
            - '@enhavo_app.maker.util'
            - '@templating.engine.twig'
        tags:
            - { name: 'maker.command' }