services:
    Enhavo\Bundle\SearchBundle\Engine\DatabaseSearch\DatabaseSearchEngine:
        arguments:
            - '@Enhavo\Bundle\SearchBundle\Index\IndexDataProvider'
            - '@Enhavo\Component\Metadata\MetadataRepository[Index]'
            - '@doctrine.orm.entity_manager'
            - '@enhavo_search.util.text_to_word'
            - '@enhavo_search.util.text_simplify'
            - '@Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\EntityResolverInterface'
            - '@Enhavo\Bundle\SearchBundle\Filter\FilterDataProvider'
            - '%enhavo_search.index.class%'
        tags:
            - { name: enhavo_search.engine }
