services:
    enhavo_search_render:
        class: Enhavo\Bundle\SearchBundle\Twig\SearchForm
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    enhavo_search_update_route:
        class: Enhavo\Bundle\SearchBundle\Twig\UpdateRoute
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\SearchBundle\Widget\SearchWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: search }

    enhavo_search.controller.search:
        class: Enhavo\Bundle\SearchBundle\Controller\SearchController
        arguments:
            - '@enhavo_search.result.result_converter'
            - '@enhavo_search.search.engine'
        calls:
            - [setContainer, ['@service_container']]

    enhavo_search.result.result_converter:
        class: Enhavo\Bundle\SearchBundle\Result\ResultConverter
        arguments:
            - '@enhavo_search.util.hightlighter'
            - '@enhavo_search.extractor.extractor'

    enhavo_search.util.hightlighter:
        class: Enhavo\Bundle\SearchBundle\Util\Highlighter
        arguments:
            - '@enhavo_search.extractor.extractor'

    enhavo_search.util.text_simplify:
        class: Enhavo\Bundle\SearchBundle\Util\TextSimplify

    enhavo_search.util.text_to_word:
        class: Enhavo\Bundle\SearchBundle\Util\TextToWord

    Enhavo\Bundle\SearchBundle\Command\IndexCommand:
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: console.command, command: 'enhavo:search:index' }

    Enhavo\Bundle\SearchBundle\Command\ReindexCommand:
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: console.command, command: 'enhavo:search:reindex' }