enhavo_media_library_index:
    path:  /media/library/index
    methods: [GET]
    options:
        expose: true
    defaults:
        _controller: enhavo_media.controller.library::indexAction
        _sylius:
            viewer:
                type: media_library
                label: media.label.library
                translation_domain: EnhavoMediaBundle

enhavo_media_library_upload:
    path:  /media/library/upload
    methods: [POST]
    options:
        expose: true
    defaults:
        _controller: enhavo_media.controller.library::uploadAction

enhavo_media_library_list:
    path:  /media/library/list
    methods: [POST, GET]
    options:
        expose: true
    defaults:
        _controller: enhavo_media.controller.file::tableAction
        _sylius:
            permission: ROLE_ENHAVO_MEDIA_LIBRARY_INDEX
            criteria:
                library: true
            sorting:
                createdAt: desc
            viewer:
                columns:
                    name:
                        type: property
                        property: filename
                        label: name
                    extension:
                        type: property
                        property: extension
                        label: extension
                    media:
                        type: media
                        property: _self
                        label: url
                        format: enhavoMediaLibraryThumb

enhavo_media_library_update:
    options:
        expose: true
    path: /media/library/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_media.controller.file::updateAction
        _sylius:
            form: Enhavo\Bundle\MediaBundle\Form\Type\LibraryFileType
            permission: ROLE_ENHAVO_MEDIA_LIBRARY_UPDATE
            viewer:
                form:
                    action: enhavo_media_library_update
                    delete: enhavo_media_library_delete
                tabs:
                    main:
                        label: file.label.file
                        translation_domain: EnhavoMediaBundle
                        template: 'admin/resource/file/library.html.twig'

enhavo_media_library_delete:
    options:
        expose: true
    path: /media/library/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_media.controller.file::deleteAction
        _sylius:
            redirect:
                route: enhavo_media_library_list

