enhavo_shop_theme_order_show:
    path: /order/{token}
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            repository:
                method: findByToken
                arguments: $token



