services:
    enhavo_media.filter_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
          - '@service_container'
          - 'MediaFilter'

    Enhavo\Bundle\MediaBundle\Filter\Filter\ImageFilter:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: image }

    Enhavo\Bundle\MediaBundle\Filter\Filter\BackgroundFilter:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: background }

    Enhavo\Bundle\MediaBundle\Filter\Filter\PDFImageFilter:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: pdf_image }

    Enhavo\Bundle\MediaBundle\Filter\Filter\VideoImageFilter:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: video_image }

    Enhavo\Bundle\MediaBundle\Filter\Filter\ImageCompressionFilter:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: image_compression }

    Enhavo\Bundle\MediaBundle\Filter\Filter\ImageBlurFilter:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: image_blur }

    Enhavo\Bundle\MediaBundle\Filter\Filter\ImageZoomFilter:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: image_zoom }

    Enhavo\Bundle\MediaBundle\Filter\Filter\ParentFilter:
        public: true
        arguments:
            - '@enhavo_media.media.format_manager'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: parent }

    Enhavo\Bundle\MediaBundle\Filter\Filter\MimetypeFilter:
        public: true
        arguments:
            - '@enhavo_media.media.format_manager'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.media_filter, alias: mimetype }
