services:
    enhavo_newsletter.storage_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'NewsletterStorage'

    enhavo_newsletter.storage.local:
        class: Enhavo\Bundle\NewsletterBundle\Storage\LocalStorage
        arguments:
            - []
            - '@doctrine.orm.entity_manager'
            - '@enhavo_newsletter.repository.subscriber'
        tags:
            - { name: enhavo.newsletter_storage, alias: local }

    enhavo_newsletter.storage.cleverreach:
        class: Enhavo\Bundle\NewsletterBundle\Storage\CleverReachStorage
        arguments:
            - '@enhavo_newsletter.cleverreach_client'
        tags:
            - { name: enhavo.newsletter_storage, alias: cleverreach}

    enhavo_newsletter.cleverreach_client:
        class: Enhavo\Bundle\NewsletterBundle\CleverReach\Client
        arguments:
            - '%enhavo_newsletter.cleverreach.credentials%'
            - '%enhavo_newsletter.default_groups%'
            - '%enhavo_newsletter.cleverreach.mapping%'
            - '@event_dispatcher'

    enhavo_newsletter.add_subscriber_listener:
        class: Enhavo\Bundle\NewsletterBundle\EventListener\SubscriberSubscriber
        arguments:
            - '@enhavo_newsletter.form_resolver'
        tags:
            - { name: kernel.event_subscriber }

    enhavo_newsletter.strategy_resolver:
        class: Enhavo\Bundle\NewsletterBundle\Strategy\StrategyResolver
        arguments:
            - '%enhavo_newsletter.forms%'
            - '@enhavo_newsletter.strategy_collector'
            - '%enhavo_newsletter.strategy%'

    enhavo_newsletter.storage_resolver:
        class: Enhavo\Bundle\NewsletterBundle\Storage\StorageResolver
        arguments:
            - '%enhavo_newsletter.forms%'
            - '@enhavo_newsletter.storage_collector'
            - '%enhavo_newsletter.storage%'

    enhavo_newsletter.form_resolver:
        class: Enhavo\Bundle\NewsletterBundle\Form\Resolver
        arguments:
            - '%enhavo_newsletter.forms%'
            - '%enhavo_newsletter.default_groups%'
            - '@enhavo_newsletter.group_manager'

    enhavo_newsletter.group_manager:
        class: Enhavo\Bundle\NewsletterBundle\Group\GroupManager
        arguments:
            - '@doctrine.orm.entity_manager'

    enhavo_newsletter.subscriber_exists_validator:
        class: Enhavo\Bundle\NewsletterBundle\Validator\Constraints\SubscriberExistsValidator
        arguments:
            - '@enhavo_newsletter.subscriber.manager'
        tags:
            - { name: validator.constraint_validator, alias: subscriber_exists }