services:
    enhavo_newsletter.twig.subscribe_renderer:
        class: Enhavo\Bundle\NewsletterBundle\Twig\SubscribeFormRenderer
        arguments:
            - '@enhavo_newsletter.form_resolver'
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\NewsletterBundle\Menu\SubscriberMenu:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: newsletter_subscriber }


    enhavo_newsletter_subscriber:
        class: '%enhavo_newsletter.form.type.subscriber.class%'
        tags:
            - { name: form.type }

    enhavo_newsletter_subscribe:
        class: Enhavo\Bundle\NewsletterBundle\Form\Type\SubscribeType
        tags:
            - { name: form.type }

    enhavo_newsletter.subscriber.manager:
        class: Enhavo\Bundle\NewsletterBundle\Subscriber\SubscriberManager
        arguments:
            - '@enhavo_newsletter.strategy_collector'
            - '%enhavo_newsletter.strategy%'
            - '@enhavo_newsletter.strategy_resolver'
            - '@enhavo_newsletter.storage_collector'
            - '%enhavo_newsletter.storage%'
            - '@enhavo_newsletter.storage_resolver'
            - '@enhavo_newsletter.form_resolver'
            - '@event_dispatcher'

    enhavo_newsletter.strategy_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'NewsletterStrategy'

    enhavo_newsletter.strategy.notify:
        class: Enhavo\Bundle\NewsletterBundle\Strategy\NotifyStrategy
        arguments:
            - '%enhavo_newsletter.strategy.notify.settings%'
            - '%enhavo_newsletter.forms%'
            - '@enhavo_newsletter.storage_resolver'
            - '@enhavo_newsletter.form_resolver'
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.newsletter_strategy, alias: notify }

    enhavo_newsletter.strategy.double_opt_in:
        class: Enhavo\Bundle\NewsletterBundle\Strategy\DoubleOptInStrategy
        arguments:
            - '%enhavo_newsletter.strategy.double_opt_in.settings%'
            - '%enhavo_newsletter.forms%'
            - '@enhavo_newsletter.storage.local'
            - '@enhavo_newsletter.storage_resolver'
            - '@enhavo_newsletter.form_resolver'
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.newsletter_strategy, alias: double_opt_in }

    enhavo_newsletter.strategy.accept:
        class: Enhavo\Bundle\NewsletterBundle\Strategy\AcceptStrategy
        arguments:
            - '%enhavo_newsletter.strategy.accept.settings%'
            - '%enhavo_newsletter.forms%'
            - '@enhavo_newsletter.storage.local'
            - '@enhavo_newsletter.storage_resolver'
            - '@enhavo_newsletter.form_resolver'
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.newsletter_strategy, alias: accept }

    enhavo_newsletter.extend_listener.subscriber:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\NewsletterBundle\Entity\Subscriber
            - '%enhavo_newsletter.model.subscriber.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }