enhavo_app:
    form_themes:
        - '@EnhavoForm/admin/form/form/fields.html.twig'
    template_paths:
        enhavo_form:
            path: '@EnhavoFormBundle/Resources/views'
            alias: EnhavoForm
            priority: 10