enhavo_navigation_navigation_index:
    options:
        expose: true
    path: /enhavo/navigation/navigation/index
    methods: [GET]
    defaults:
        _controller: enhavo_navigation.controller.navigation:indexAction
        _sylius:
            viewer:
                title: navigation.label.navigation
                translationDomain: EnhavoNavigationBundle

enhavo_navigation_navigation_create:
    options:
        expose: true
    path: /enhavo/navigation/navigation/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_navigation.controller.navigation:createAction
        _sylius:
            redirect: enhavo_navigation_navigation_update
            viewer:
                translationDomain: EnhavoNavigationBundle
                tabs:
                    main:
                        label: navigation.label.navigation
                        template: EnhavoNavigationBundle:Admin/Navigation:main.html.twig
                    nodes:
                        label: navigation.label.items
                        template: EnhavoNavigationBundle:Admin/Navigation:nodes.html.twig

enhavo_navigation_navigation_update:
    options:
        expose: true
    path: /enhavo/navigation/navigation/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_navigation.controller.navigation:updateAction
        _sylius:
            viewer:
                translationDomain: EnhavoNavigationBundle
                tabs:
                    main:
                        label: navigation.label.navigation
                        template: EnhavoNavigationBundle:Admin/Navigation:main.html.twig
                    nodes:
                        label: navigation.label.items
                        template: EnhavoNavigationBundle:Admin/Navigation:nodes.html.twig

enhavo_navigation_navigation_table:
    options:
        expose: true
    path: /enhavo/navigation/navigation/table
    defaults:
        _controller: enhavo_navigation.controller.navigation:tableAction
        _sylius:
            paginate: 50
            viewer:
                translationDomain: EnhavoNavigationBundle
                columns:
                    name:
                        type: text
                        property: name
                        label: navigation.label.name
                        width: 10

enhavo_navigation_navigation_delete:
    options:
        expose: true
    path: /enhavo/navigation/navigation/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_navigation.controller.navigation:deleteAction