Enhavo\Bundle\NewsletterBundle\Model\Subscriber:
    properties:
        email:
            - Email: ~
            - NotBlank: ~
    constraints:
        - Enhavo\Bundle\NewsletterBundle\Validator\Constraints\SubscriberExists:

Enhavo\Bundle\NewsletterBundle\Entity\Newsletter:
    properties:
        subject:
            - NotBlank: ~
