services:
    Enhavo\Bundle\FormBundle\Form\Type\ListType:
        class: Enhavo\Bundle\FormBundle\Form\Type\ListType
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Type\PolyCollectionType:
        arguments:
            - '@Enhavo\Bundle\FormBundle\Prototype\PrototypeManager'
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Type\DateType:
        arguments:
            - '%enhavo_form.date_type.config%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Type\DateTimeType:
        arguments:
            - '%enhavo_form.date_time_type.config%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Type\BooleanType:
        arguments:
            - '@translator'
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Type\PositionType:
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Type\WysiwygType:
        arguments:
            - '%enhavo_form.wysiwyg.editor_entrypoint%'
            - '%enhavo_form.wysiwyg.editor_entrypoint_build%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Type\AutoCompleteEntityType:
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@property_accessor'
            - '@enhavo_app.action_manager'
        tags:
            - { name: form.type, alias: 'enhavo_auto_complete_entity' }

    Enhavo\Bundle\FormBundle\Form\Type\CurrencyType:
        arguments:
            - '@Enhavo\Bundle\FormBundle\Form\Transformer\CurrencyTransformer'
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Type\ConditionalType:
        arguments:
            - '@Enhavo\Bundle\VueFormBundle\Form\VueForm'
        tags:
            - { name: form.type }

    Enhavo\Bundle\FormBundle\Form\Extension\ChoiceTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    Enhavo\Bundle\FormBundle\Form\Extension\EntityTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Bridge\Doctrine\Form\Type\EntityType }

    Enhavo\Bundle\FormBundle\Form\Extension\ConditionTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Enhavo\Bundle\FormBundle\Form\Extension\ActionExtension:
        arguments:
            - '@enhavo_app.action_manager'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Enhavo\Bundle\FormBundle\Form\Transformer\CurrencyTransformer:
        public: true
        arguments:
            - '@Enhavo\Bundle\FormBundle\Formatter\CurrencyFormatter'

    Enhavo\Bundle\FormBundle\Form\Type\AutoSuggestEntityType:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
