enhavo_setting_setting_index:
    options:
        expose: true
    path: /enhavo/setting/setting/index
    methods: [GET]
    defaults:
        _controller: enhavo_setting.controller.setting:indexAction
        _sylius:
            viewer:
                title: label.setting
                translationDomain: EnhavoSettingBundle
                actions:
                    create:
                        type: create
                        display: false

enhavo_setting_setting_update:
    options:
        expose: true
    path: /enhavo/setting/setting/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_setting.controller.setting:updateAction
        _sylius:
            viewer:
                translationDomain: EnhavoSettingBundle
                form:
                    delete: ~
                buttons:
                    delete:
                        display: false
                tabs:
                    main:
                        label: setting.label.setting
                        template: EnhavoSettingBundle:Setting:setting.html.twig

enhavo_setting_setting_table:
    options:
        expose: true
    path: /enhavo/setting/setting/table
    methods: [GET]
    defaults:
        page: 1
        _controller: enhavo_setting.controller.setting:tableAction
        _sylius:
            viewer:
                translationDomain: EnhavoSettingBundle
                columns:
                    label:
                        type: label
                        property: label
                        label: setting.label.label
                        width: 6
                    value:
                        type: text
                        property: setting
                        label: setting.label.value
                        width: 6
