enhavo_user_theme_api_reset_password_request:
    path: /reset-password/request
    methods: [GET, POST]
    defaults:
        _format: json
        _config: theme
        _expose: api
        _endpoint:
            type: Enhavo\Bundle\UserBundle\Endpoint\Type\ResetPassword\ResetPasswordRequestEndpointType


enhavo_user_theme_api_reset_password_confirm:
    path: /reset-password/confirm/{token}
    methods: [GET, POST]
    defaults:
        _format: json
        _config: theme
        _expose: api
        _endpoint:
            type: Enhavo\Bundle\UserBundle\Endpoint\Type\ResetPassword\ResetPasswordConfirmEndpointType

