services:
    Enhavo\Bundle\ShopBundle\Menu\ProductMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_product }

    Enhavo\Bundle\ShopBundle\Menu\OrderMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_order }

    Enhavo\Bundle\ShopBundle\Menu\ProductOptionMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_product_option }

    Enhavo\Bundle\ShopBundle\Menu\ProductAttributeMenu:
            parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
            tags:
                - { name: enhavo.menu, alias: shop_product_attribute }

    Enhavo\Bundle\ShopBundle\Menu\ProductAssociationTypeMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_product_association_type }

    Enhavo\Bundle\ShopBundle\Menu\TaxCategoryMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_tax_category }

    Enhavo\Bundle\ShopBundle\Menu\TaxRateMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_tax_rate }

    Enhavo\Bundle\ShopBundle\Menu\VoucherMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_voucher }

    Enhavo\Bundle\ShopBundle\Menu\ShopMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\ListMenu
        tags:
            - { name: enhavo.menu, alias: shop }

    Enhavo\Bundle\ShopBundle\Menu\CategoryMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_category }

    Enhavo\Bundle\ShopBundle\Menu\TagMenuType:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_tag }