services:
    Enhavo\Bundle\ShopBundle\Context\SessionCartContext:
        arguments:
            - '@session'
            - 'enhavo_shop_cart'
            - '@sylius.repository.order'
            - '@sylius.factory.order'
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
        tags:
            - { name: sylius.context.cart, priority: -777 }

    Enhavo\Bundle\ShopBundle\OrderProcessing\OrderAdjustmentsClearer:
        tags:
            - { name: sylius.order_processor, priority: 60 }

    Enhavo\Bundle\ShopBundle\OrderProcessing\OrderAddressAssigner:
        arguments:
            - '@enhavo_shop.order_manager'
        tags:
            - { name: sylius.order_processor, priority: 60 }


    Enhavo\Bundle\ShopBundle\OrderProcessing\OrderPricesCalculator:
        arguments:
            - '@Enhavo\Bundle\ShopBundle\Manager\PricingManager'
        tags:
            - { name: sylius.order_processor, priority: 60 }

    Enhavo\Bundle\ShopBundle\OrderProcessing\OrderTaxProcessor:
        arguments:
            - '@Enhavo\Bundle\ShopBundle\Manager\TaxationManager'
        tags:
            - { name: sylius.order_processor, priority: 60 }

    Enhavo\Bundle\ShopBundle\OrderProcessing\OrderShipmentProcessor:
        arguments:
            - '@sylius.shipping_method_resolver.default'
            - '@sylius.factory.shipment'
            - '@sylius.shipping_methods_resolver'
        tags:
            - { name: sylius.order_processor, priority: 40 }

    Enhavo\Bundle\ShopBundle\Manager\TaxationManager:

    Enhavo\Bundle\ShopBundle\Manager\PricingManager:

    Enhavo\Bundle\ShopBundle\Manager\OrderManager:
        arguments:
            - '@Enhavo\Bundle\ShopBundle\Address\AddressProviderInterface'
            - '@enhavo_app.util.secure_url_token_generator'
            - '@Enhavo\Bundle\AppBundle\Mailer\MailerManager'

    enhavo_shop.order_manager:
        public: true
        alias: Enhavo\Bundle\ShopBundle\Manager\OrderManager

    Enhavo\Bundle\ShopBundle\Pricing\DefaultPriceCalculator:
        arguments:
            - '@sylius.tax_calculator'
            - '@sylius.tax_rate_resolver'
        tags:
            - { name: enhavo_shop.price_calculator, priority: 10 }

    Enhavo\Bundle\ShopBundle\Taxation\Applicator\OrderItemsTaxesApplicator:
        arguments:
            - '@sylius.tax_calculator'
            - '@sylius.factory.adjustment'
            - '@sylius.tax_rate_resolver'
        tags:
            - { name: enhavo_shop.order_taxes_applicator, priority: 10 }

    Enhavo\Bundle\ShopBundle\Action\BillingActionType:
        parent: Enhavo\Bundle\AppBundle\Action\Type\DownloadActionType
        public: true
        tags:
            - { name: enhavo.action, alias: 'shop_billing' }

    Enhavo\Bundle\ShopBundle\Action\PackingSlipActionType:
        parent: Enhavo\Bundle\AppBundle\Action\Type\DownloadActionType
        public: true
        tags:
            - { name: enhavo.action, alias: 'shop_packing_slip' }

    Enhavo\Bundle\ShopBundle\Action\CancelActionType:
        parent: Enhavo\Bundle\AppBundle\Action\Type\TransitionActionType
        public: true
        tags:
            - { name: enhavo.action, alias: 'shop_order_cancel' }

    Enhavo\Bundle\ShopBundle\Action\PaidActionType:
        parent: Enhavo\Bundle\AppBundle\Action\Type\TransitionActionType
        public: true
        tags:
            - { name: enhavo.action, alias: 'shop_order_paid' }

    Enhavo\Bundle\ShopBundle\Action\RefundActionType:
        parent: Enhavo\Bundle\AppBundle\Action\Type\TransitionActionType
        public: true
        tags:
            - { name: enhavo.action, alias: 'shop_order_refund' }

    Enhavo\Bundle\ShopBundle\Action\ShipActionType:
        parent: Enhavo\Bundle\AppBundle\Action\Type\TransitionActionType
        public: true
        tags:
            - { name: enhavo.action, alias: 'shop_order_ship' }

    enhavo.state_resolver.order:
        public: true
        alias: Enhavo\Bundle\ShopBundle\StateResolver\OrderStateResolver

    Enhavo\Bundle\ShopBundle\StateResolver\OrderStateResolver:
        arguments:
            - '@sm.factory'

#    enhavo.order_processing.shipment_processor:
#        class: Enhavo\Bundle\ShopBundle\OrderProcessing\OrderShipmentProcessor
#        arguments:
#            - '@sylius.resolver.default_shipping_method'
#            - '@sylius.factory.shipment'
#            - '@sylius.shipping_calculator'
#            - '@enhavo.shipping.shipping_tax_calculator'
#            - '@sylius.factory.adjustment'
#
#    enhavo.order_processing.tax_processor:
#        class: Enhavo\Bundle\ShopBundle\OrderProcessing\OrderTaxProcessor
#        arguments:
#            - '@sylius.factory.adjustment'
#
#    enhavo.shipping.shipping_tax_calculator:
#        class: Enhavo\Bundle\ShopBundle\Shipping\ShippingTaxCalculator
#
#    enhavo.order_processing.payment_processor:
#        class: Enhavo\Bundle\ShopBundle\OrderProcessing\OrderPaymentProcessor
#
#    enhavo.order_processing.addressing_processor:
#        class: Enhavo\Bundle\ShopBundle\OrderProcessing\OrderAddressingProcessor
#        arguments:
#            - '@enhavo.order_processing.shipment_processor'
#
#    enhavo.order_processing.confirm_processor:
#        class: Enhavo\Bundle\ShopBundle\OrderProcessing\OrderConfirmProcessor
#        arguments:
#            - '@sylius.cart_provider'
#            - '@enhavo_shop.mailer.confirm_mailer'
#            - '@enhavo_shop.mailer.notification_mailer'
#            - '@enhavo_shop.order.number_generator'
#            - '@enhavo_shop.order.order_address_provider'
#            - '@enhavo_shop.manager.coupon'
#
#    enhavo_shop.order.number_generator:
#        class: Enhavo\Bundle\ShopBundle\Order\OrderNumberGenerator
#        arguments:
#            - '@sylius.repository.order'
#
#    enhavo.order_processing.init_processor:
#        class: Enhavo\Bundle\ShopBundle\OrderProcessing\OrderInitProcessor
#        arguments:
#            - '@enhavo_app.util.secure_url_token_generator'
#            - '@security.token_storage'
#
#    enhavo.order_processing.tracking_processor:
#        class: Enhavo\Bundle\ShopBundle\OrderProcessing\OrderTrackingProcessor
#        arguments:
#            - '@enhavo_shop.mailer.tracking_mailer'
#
#    enhavo.order_processing.purchase_processor:
#        class: Enhavo\Bundle\ShopBundle\OrderProcessing\OrderPurchaseProcessor
#        calls:
#            - [setContainer, ['@service_container']]
#
#    enhavo.shop.cart_item_resolver:
#        class: Enhavo\Bundle\ShopBundle\Cart\ItemResolver
#        arguments:
#            - '@sylius.repository.product'
#            - '@sylius.order_item_quantity_modifier'
#
#    enhavo_shop.listener.cart_subscriber:
#        class: Enhavo\Bundle\ShopBundle\EventListener\CartSubscriber
#        arguments:
#            - '@enhavo.order_processing.shipment_processor'
#            - '@sylius.promotion_processor'
#            - '@enhavo.order_processing.init_processor'
#            - '@enhavo.order_processing.tax_processor'
#            - '@doctrine.orm.entity_manager'
#        tags:
#            - { name: kernel.event_subscriber }
#
#    enhavo_shop.listener.order_subscriber:
#        class: Enhavo\Bundle\ShopBundle\EventListener\OrderSubscriber
#        arguments:
#            - '@enhavo.order_processing.tracking_processor'
#        tags:
#            - { name: kernel.event_subscriber }
#
#    enhavo_shop.listener.user_subscriber:
#        class: Enhavo\Bundle\ShopBundle\EventListener\UserSubscriber
#        arguments:
#            - '@enhavo_shop.cart.user_cart_merger'
#        tags:
#            - { name: kernel.event_subscriber }
#
#    enhavo_shop.cart.user_cart_merger:
#        class: Enhavo\Bundle\ShopBundle\Cart\UserCartMerger
#        arguments:
#            - '@enhavo_shop.cart.user_cart_provider'
#            - '@sylius.cart_provider'
#            - '@sylius.context.cart'
#            - '@doctrine.orm.default_entity_manager'
#
#    enhavo_shop.cart.user_cart_provider:
#        class: Enhavo\Bundle\ShopBundle\Cart\UserCartProvider
#        arguments:
#            - '@security.token_storage'
#            - '@sylius.repository.cart'
#            - '@event_dispatcher'
#
#    enhavo_shop.validator.order_addressing:
#        class:  Enhavo\Bundle\ShopBundle\Validator\Constraints\OrderAddressingValidator
#        arguments:
#            - '@validator'
#        tags:
#            - { name: validator.constraint_validator, alias: order_addressing }
#
#    enhavo_shop.validator.order_payment:
#        class:  Enhavo\Bundle\ShopBundle\Validator\Constraints\OrderPaymentValidator
#        arguments:
#            - '@validator'
#        tags:
#            - { name: validator.constraint_validator, alias: order_payment }
#
#    enhavo_shop.controller.checkout:
#        class: 'Enhavo\Bundle\ShopBundle\Controller\CheckoutController'
#        public: true
#        arguments:
#            - '@sylius.resource_controller.request_configuration_factory'
#            - '@Enhavo\Component\Type\FactoryInterface[View]'
#        calls:
#            - [setContainer, ['@service_container']]
#
#    enhavo_shop.controller.payment:
#        class: Enhavo\Bundle\ShopBundle\Controller\PaymentController
#        public: true
#        arguments:
#            - '@sylius.resource_controller.request_configuration_factory'
#            - '@Enhavo\Component\Type\FactoryInterface[View]'
#        calls:
#            - [setContainer, ['@service_container']]
#
#    enhavo_shop.order.order_address_provider:
#        class: Enhavo\Bundle\ShopBundle\Order\OrderAddressProvider
#        arguments:
#            - '@sylius.factory.address'
#            - '@enhavo_shop.order.order_provider'
#            - '@doctrine.orm.entity_manager'
#
#    enhavo_shop.order.order_provider:
#        class: Enhavo\Bundle\ShopBundle\Order\OrderProvider
#        arguments:
#            - '@sylius.repository.order'
#
#    enhavo_shop.cart.cart_transfer:
#        class: Enhavo\Bundle\ShopBundle\Cart\CartTransfer
#        arguments:
#            - '@sylius.order_item_quantity_modifier'
#            - '@sylius.factory.order_item'
#            - '@event_dispatcher'
#            - '@session'
#        calls:
#            - [setContainer, ['@service_container']]
#
#    Enhavo\Bundle\ShopBundle\Widget\ProductListWidget:
#        public: true
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - { name: enhavo.widget, alias: 'shop_product_list' }
#
#    Enhavo\Bundle\ShopBundle\Widget\UserAddressWidget:
#        public: true
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - { name: enhavo.widget, alias: 'shop_user_address' }
#
#    Enhavo\Bundle\ShopBundle\Widget\CartSummaryWidget:
#        public: true
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - { name: enhavo.widget,  alias: 'shop_cart_summary' }
#
#    Enhavo\Bundle\ShopBundle\Widget\CouponRedeemWidget:
#        public: true
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - { name: enhavo.widget,  alias: 'shop_coupon_redeem' }
#
#    Enhavo\Bundle\ShopBundle\Widget\ProductConfiguratorWidget:
#        public: true
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - { name: enhavo.widget,  alias: 'shop_product_configurator' }
#
#    Enhavo\Bundle\ShopBundle\Widget\OrderHistoryWidget:
#        public: true
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#            - { name: enhavo.widget,  alias: 'shop_order_history' }
#
#    enhavo_shop.document.billing_generator:
#        class: Enhavo\Bundle\ShopBundle\Document\BillingGenerator
#        arguments:
#            - '@service_container'
#
#    enhavo_shop.document.packing_slip_generator:
#        class: Enhavo\Bundle\ShopBundle\Document\PackingSlipGenerator
#        arguments:
#            - '@service_container'
#
#    enhavo_shop.mailer.confirm_mailer_default:
#        class: Enhavo\Bundle\ShopBundle\Mailer\ConfirmMailer
#        arguments:
#            - '@mailer'
#            - '@twig'
#            - '%enhavo_shop.mailer.confirm%'
#        calls:
#            - [setContainer, ['@service_container']]
#
#    enhavo_shop.mailer.tracking_mailer_default:
#        class: Enhavo\Bundle\ShopBundle\Mailer\TrackingMailer
#        arguments:
#            - '@mailer'
#            - '@twig'
#            - '%enhavo_shop.mailer.tracking%'
#        calls:
#            - [setContainer, ['@service_container']]
#
#    enhavo_shop.mailer.notification_mailer_default:
#        class: Enhavo\Bundle\ShopBundle\Mailer\NotificationMailer
#        arguments:
#            - '@mailer'
#            - '@twig'
#            - '%enhavo_shop.mailer.notification%'
#        calls:
#            - [setContainer, ['@service_container']]
#
#    enhavo_shop.event_listner.serializer_subscriber:
#        class: Enhavo\Bundle\ShopBundle\EventListener\SerializerSubscriber
#        tags:
#          - { name: jms_serializer.event_subscriber }
#
#
#    enhavo_shop.chart.order_chart_provicer:
#        class: Enhavo\Bundle\ShopBundle\Chart\OrderChartProvider
#        arguments:
#          - '@sylius.repository.order'
#        calls:
#            - [setContainer, ['@service_container']]
#        tags:
#          - { name: enhavo.chart_provider, alias: 'shop_order' }
#
