parameters:
    enhavo_shop.controller.user.class: Enhavo\Bundle\ShopBundle\Controller\UserController

services:
    enhavo_shop.listener.doctrine_sylius_meta:
        class: Enhavo\Bundle\ShopBundle\EventListener\DoctrineSyliusMetaListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Enhavo\Bundle\ShopBundle\Table\Widget\AddressWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.table_widget, alias: shop_address }

    Enhavo\Bundle\ShopBundle\Table\Widget\ProductVariantWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.table_widget, alias: shop_product_variant }

    Enhavo\Bundle\ShopBundle\Table\Widget\OrderStateWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.table_widget, alias: order_state }

    enhavo_shop.locale.country_resolver:
        class: Enhavo\Bundle\ShopBundle\Locale\CountryResolver
        arguments:
            - '@sylius.repository.country'

    Enhavo\Bundle\ShopBundle\Menu\ProductMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_product }

    Enhavo\Bundle\ShopBundle\Menu\OrderMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_order }

    Enhavo\Bundle\ShopBundle\Menu\ProductOptionMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_product_option }

    Enhavo\Bundle\ShopBundle\Menu\VoucherMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop_voucher }

    Enhavo\Bundle\ShopBundle\Menu\ShopMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: shop }

    Enhavo\Bundle\ShopBundle\Button\BillingButton:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.button, alias: shop_billing }

    Enhavo\Bundle\ShopBundle\Button\PackingSlipButton:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.button, alias: shop_packing_slip }

    enhavo_shop.document.manager:
        class: Enhavo\Bundle\ShopBundle\Document\DocumentManager
        calls:
            - [setContainer, ['@service_container']]

    sylius.invoice_number_generator:
        class: Enhavo\Bundle\ShopBundle\Document\InvoiceNumberGenerator

    enhavo_shop.twig.country:
        class: Enhavo\Bundle\ShopBundle\Twig\Country
        tags:
            - { name: twig.extension }

    enhavo_shop.extend_listener.product:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\ShopBundle\Entity\Product
            - '%sylius.model.product.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_shop.extend_listener.order:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\ShopBundle\Entity\Order
            - '%sylius.model.order.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_shop.controller.user:
        class: '%enhavo_shop.controller.user.class%'
        arguments:
            - '@sylius.resource_controller.request_configuration_factory'
            - '@view.factory'
            - '@fos_rest.view_handler'
        calls:
            - [setContainer, ['@service_container']]

    enhavo_shop.factory.voucher:
        class: '%enhavo_shop.factory.voucher.class%'
        arguments:
            - '%enhavo_shop.model.voucher.class%'
        calls:
            - [setContainer, ['@service_container']]

    enhavo_shop.manager.voucher_manager:
        class: Enhavo\Bundle\ShopBundle\Manager\VoucherManager
        calls:
            - [setContainer, ['@service_container']]

    enhavo_shop.manager.coupon:
        class: Enhavo\Bundle\ShopBundle\Manager\CouponManager
        calls:
            - [setContainer, ['@service_container']]