enhavo_newsletter_subscribe_activate:
    pattern: /newsletter/activate/{token}/{type}
    options:
        expose: true
    defaults:
        _controller: enhavo_newsletter.controller.subscriber:activateAction

enhavo_newsletter_subscribe_accept:
    pattern: /newsletter/accept/{token}/{type}
    options:
        expose: true
    defaults:
        _controller: enhavo_newsletter.controller.subscriber:acceptAction

enhavo_newsletter_subscribe_add:
    path: /newsletter/add/{type}
    options:
        expose: true
    defaults:
        _controller: enhavo_newsletter.controller.subscriber:addAction
        _sylius:
            form: enhavo_newsletter_subscribe
    methods: [POST]