enhavo_shop_order_index:
    options:
        expose: true
    path: /enhavo/shop/order/index
    methods: [GET]
    defaults:
        _controller: sylius.controller.order::indexAction
        _sylius:
            viewer:
                title: order.label.order
#                stylesheets:
#                    - '@EnhavoShopBundle/Resources/public/css/order.css'
                translation_domain: EnhavoShopBundle
                app: shop/OrderApp
                blocks:
                    table:
                        type: table
                        table_route: enhavo_shop_order_table
                        open_route: enhavo_shop_order_update
                actions:
                    create:
                        route: ~
                        hidden: true

enhavo_shop_order_update:
    options:
        expose: true
    path: /enhavo/shop/order/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.order::updateAction
        _sylius:
            form: enhavo_shop_order
            viewer:
                form:
                    action: enhavo_shop_order_update
                    delete: enhavo_shop_order_delete
                tabs:
                    main:
                        label: order.label.order
                        translation_domain: EnhavoShopBundle
                        template: EnhavoShopBundle:Admin:Order/Tab/order.html.twig
                    address:
                        label: order.label.address
                        translation_domain: EnhavoShopBundle
                        template: EnhavoShopBundle:Admin:Order/Tab/address.html.twig
                    payment:
                        label: order.label.payment
                        translation_domain: EnhavoShopBundle
                        template: EnhavoShopBundle:Admin:Order/Tab/payment.html.twig
                buttons:
                    billing:
                        type: shop_billing
                    packingSlip:
                        type: shop_packing_slip

enhavo_shop_order_table:
    options:
        expose: true
    path: /enhavo/shop/order/table
    defaults:
        page: 1
        _controller: sylius.controller.order::tableAction
        _sylius:
            filters:
                number:
                    type: text
                    property: number
                    label: order.label.number
                    translation_domain: EnhavoShopBundle
            sorting:
                orderedAt: desc
            criteria:
                checkoutState: completed
            viewer:
                translation_domain: EnhavoShopBundle
                batch_route: enhavo_shop_order_batch
                columns:
                    number:
                        type: text
                        label: order.label.number
                        property: number
                        width: 2
                    date:
                        type: datetime
                        label: order.label.ordered_at
                        property: orderedAt
                        width: 2
                    name:
                        type: shop_address
                        label: order.label.name
                        property: shippingAddress
                        width: 4
                    payed:
                        type: order_state
                        label: order.label.payed
                        property: payed
                        width: 1
                    packed:
                        type: order_state
                        label: order.label.packed
                        property: packed
                        width: 1
                    shipped:
                        type: order_state
                        label: order.label.shipped
                        property: shipped
                        width: 1
                    cancelled:
                        type: order_state
                        label: order.label.cancelled
                        property: cancelled
                        width: 1

enhavo_shop_order_delete:
    options:
        expose: true
    path: /enhavo/shop/order/delete/{id}
    methods: [POST]
    defaults:
        _controller: sylius.controller.order::deleteAction

enhavo_shop_order_batch:
    options:
        expose: true
    path: /enhavo/shop/order/batch
    methods: [POST]
    defaults:
        _controller: sylius.controller.order::batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete

enhavo_shop_order_billing:
    options:
        expose: true
    path: /enhavo/shop/order/{id}/billing.pdf
    methods: [GET]
    defaults:
        _controller: sylius.controller.order::billingAction
        _sylius:
            form: enhavo_shop_order

enhavo_shop_order_packing_slip:
    options:
        expose: true
    path: /enhavo/shop/order/{id}/packing-slip.pdf
    methods: [GET]
    defaults:
        _controller: sylius.controller.order::packingSlipAction
        _sylius:
            form: enhavo_shop_order
