sylius_product_index:
    options:
        expose: true
    path: /enhavo/shop/product/index
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            viewer:
                label: product.label.product
                translation_domain: EnhavoShopBundle

sylius_product_create:
    options:
        expose: true
    path: /enhavo/shop/product/create
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            redirect: sylius_product_update
            viewer:
                tabs:
                    main:
                        label: Product
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/product.html.twig
                    dimension:
                        label: Dimension
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/dimension.html.twig
                    options:
                        label: Options
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/options.html.twig
                    taxonomy:
                        label: Taxonomie
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/taxonomy.html.twig
                    meta:
                        label: Meta
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/meta.html.twig

sylius_product_update:
    options:
        expose: true
    path: /enhavo/shop/product/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            viewer:
                tabs:
                    main:
                        label: Product
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/product.html.twig
                    dimension:
                        label: Dimension
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/dimension.html.twig
                    options:
                        label: Options
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/options.html.twig
                    taxonomy:
                        label: Taxonomie
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/taxonomy.html.twig
                    meta:
                        label: Meta
                        translation_domain: EnhavoShopBundle
                        template: admin/resource/product/meta.html.twig
                actions:
                    variant:
                        icon: book
                        type: shop_variant

sylius_product_table:
    options:
        expose: true
    path: /enhavo/shop/product/table
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product:tableAction
        _sylius:
            viewer:
                columns:
                    title:
                        property: title
                        width: 4
                        label: product.form.label.title
                        translation_domain: EnhavoShopBundle
                        type: text
                    price:
                        property: price
                        width: 2
                        label: product.form.label.price
                        translation_domain: EnhavoShopBundle
                        type: currency
                        currency: â‚¬
                    active:
                        property: enabled
                        width: 1
                        label: product.form.label.active
                        translation_domain: EnhavoShopBundle
                        type: boolean
                    action:
                        width: 2
                        label: product.label.variants
                        translation_domain: EnhavoShopBundle
                        type: action
                        action:
                            type: shop_variant

sylius_product_delete:
    options:
        expose: true
    path: /enhavo/shop/product/delete/{id}
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:deleteAction

sylius_product_batch:
    options:
        expose: true
    path: /enhavo/shop/product/batch
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete

sylius_product_preview:
    options:
        expose: true
    path: /enhavo/shop/product/preview
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:previewAction
        _sylius:
            viewer:

sylius_product_resource_preview:
    options:
        expose: true
    path: /enhavo/shop/product/resource/preview
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:previewResourceAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_article.controller.article:showResourceAction

sylius_product_auto_complete:
   options:
       expose: true
   path: /enhavo/shop/product/{id}/auto_complete
   methods: [GET]
   defaults:
       _controller: enhavo_form.controller.auto_complete:searchAction
       _config:
           class: Enhavo\Bundle\ShopBundle\Entity\Product
           repository:
               method: findByTerm
               arguments:
                  - expr:configuration.getSearchTerm()
                  - expr:request.get('id')
                  - expr:configuration.getLimit()
           choice_label: name

sylius_product_variant_generate:
    path: /enhavo/shop/product/{id}/variants/generate
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            form: Enhavo\Bundle\ShopBundle\Form\Type\ProductGenerateVariantsType
