sylius_product_attribute_index:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/index
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_attribute:indexAction
        _sylius:
            viewer:
                actions:
                    create:
                        type: shop_create_attribute
                        route: sylius_product_attribute_create

sylius_product_attribute_create:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/{$type}/create
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product_attribute:createAction
        _sylius:
            factory:
                method: createTyped
                arguments: $type
            redirect: sylius_product_attribute_update
            form:
                options:
                    validation_groups: [ form ]
            viewer:

sylius_product_attribute_create_form:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/create/form
    methods: [GET,POST]
    controller: enhavo_app.controller.modal:formAction
    defaults:
        _config:
            form: Enhavo\Bundle\ShopBundle\Form\Type\ProductAttributeTypeType

sylius_product_attribute_update:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product_attribute:updateAction
        _sylius:
            form:
                options:
                    validation_groups: [ form ]
            viewer:

sylius_product_attribute_table:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/table
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product_attribute:tableAction
        _sylius:
            viewer:
                columns:
                    id:
                        property: id
                        width: 1
                        label: ID
                        type: property
                    code:
                        property: code
                        width: 3
                        label: Code
                        type: text
                    type:
                        property: type
                        width: 3
                        label: Type
                        type: text

sylius_product_attribute_delete:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/delete/{id}
    methods: [POST]
    defaults:
        _controller: sylius.controller.product_attribute:deleteAction

sylius_product_attribute_batch:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/batch
    methods: [POST]
    defaults:
        _controller: sylius.controller.product_attribute:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete

sylius_product_attribute_preview:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/preview
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_attribute:previewAction
        _sylius:
            viewer:

sylius_product_attribute_resource_preview:
    options:
        expose: true
    path: /enhavo/shop/product/attribute/resource/preview
    methods: [POST]
    defaults:
        _controller: sylius.controller.product_attributes:previewResourceAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_article.controller.article:showResourceAction
