sylius_tax_category_index:
    options:
        expose: true
    path: /enhavo/shop/tax/category/index
    methods: [GET]
    defaults:
        _controller: sylius.controller.tax_category::indexAction
        _sylius:
            viewer:

sylius_tax_category_create:
    options:
        expose: true
    path: /enhavo/shop/tax/category/create
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.tax_category::createAction
        _sylius:
            redirect: sylius_tax_category_update
            viewer:

sylius_tax_category_update:
    options:
        expose: true
    path: /enhavo/shop/tax/category/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.tax_category::updateAction
        _sylius:
            viewer:

sylius_tax_category_table:
    options:
        expose: true
    path: /enhavo/shop/tax/category/table
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.tax_category::tableAction
        _sylius:
            viewer:
                columns:
                    id:
                        property: id
                        width: 1
                        label: id
                        type: property
                    name:
                        property: name
                        width: 3
                        label: Name
                        type: property
                    code:
                        property: code
                        width: 2
                        label: Code
                        type: property
                    description:
                        property: description
                        width: 6
                        label: Description
                        type: property

sylius_tax_category_delete:
    options:
        expose: true
    path: /enhavo/shop/tax/category/delete/{id}
    methods: [POST]
    defaults:
        _controller: sylius.controller.tax_category::deleteAction

sylius_tax_category_batch:
    options:
        expose: true
    path: /enhavo/shop/tax/category/batch
    methods: [POST]
    defaults:
        _controller: sylius.controller.tax_category::batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete

sylius_tax_category_preview:
    options:
        expose: true
    path: /enhavo/shop/tax/category/preview
    methods: [GET]
    defaults:
        _controller: sylius.controller.tax_category::previewAction
        _sylius:
            viewer:

sylius_tax_category_resource_preview:
    options:
        expose: true
    path: /enhavo/shop/tax/category/resource/preview
    methods: [POST]
    defaults:
        _controller: sylius.controller.tax_category::previewResourceAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_article.controller.article:showResourceAction

