enhavo_shop_voucher_index:
    options:
        expose: true
    path: /enhavo/shop/voucher/index
    methods: [GET]
    defaults:
        _controller: enhavo_shop.controller.voucher::indexAction
        _sylius:
            viewer:
                title: voucher.label.voucher
                translation_domain: EnhavoShopBundle

enhavo_shop_voucher_create:
    options:
        expose: true
    path: /enhavo/shop/voucher/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_shop.controller.voucher::createAction
        _sylius:
            redirect: enhavo_shop_voucher_update
            viewer:
                translation_domain: EnhavoShopBundle

enhavo_shop_voucher_update:
    options:
        expose: true
    path: /enhavo/shop/voucher/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_shop.controller.voucher::updateAction
        _sylius:
            viewer:
                translation_domain: EnhavoShopBundle

enhavo_shop_voucher_table:
    options:
        expose: true
    path: /enhavo/shop/voucher/table
    defaults:
        _controller: enhavo_shop.controller.voucher::tableAction
        _sylius:
            viewer:
                translation_domain: EnhavoShopBundle
                columns:
                    code:
                        label: voucher.label.code
                        property: code
                        width: 4
                    amount:
                        label: voucher.label.amount
                        property: amount
                        type: template
                        template: EnhavoShopBundle:Admin/Table:currency.html.twig
                        width: 4
                    available:
                        label: voucher.label.availableAmount
                        property: availableAmount
                        type: template
                        template: EnhavoShopBundle:Admin/Table:currency.html.twig
                        width: 4

enhavo_shop_voucher_delete:
    options:
        expose: true
    path: /enhavo/shop/voucher/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_shop.controller.voucher::deleteAction

enhavo_shop_voucher_batch:
    options:
        expose: true
    path: /enhavo/shop/voucher/batch
    methods: [POST]
    defaults:
        _controller: enhavo_shop.controller.voucher::batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete
