enhavo_slider_slide_index:
    options:
        expose: true
    path: /enhavo/slider/slide/index
    methods: [GET]
    defaults:
        _controller: enhavo_slider.controller.slide:indexAction
        _sylius:
            template: EnhavoAppBundle:Resource:index.html.twig
        _viewer:

enhavo_slider_slide_create:
    options:
        expose: true
    path: /enhavo/slider/slide/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_slider.controller.slide:createAction
        _sylius:
            template: EnhavoAppBundle:Resource:create.html.twig
        _viewer:
            translationDomain: EnhavoSliderBundle
            sorting:
                sortable: true
                position: position
                initial: max

enhavo_slider_slide_update:
    options:
        expose: true
    path: /enhavo/slider/slide/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_slider.controller.slide:updateAction
        _sylius:
            template: EnhavoAppBundle:Resource:update.html.twig
        _viewer:
            translationDomain: EnhavoSliderBundle

enhavo_slider_slide_table:
    options:
        expose: true
    path: /enhavo/slider/slide/table/{page}
    methods: [GET]
    defaults:
        page: 1
        _controller: enhavo_slider.controller.slide:tableAction
        _sylius:
            template: EnhavoAppBundle:Resource:table.html.twig
            sorting:
                position: desc
        _viewer:
            translationDomain: EnhavoSliderBundle
            table:
                sorting:
                    sortable: true
                    move_after_route: enhavo_slider_slide_move_after
                    move_to_page_route: enhavo_slider_slide_move_to_page
                columns:
                    id:
                        label: slide.label.id
                        property: id
                        width: 1
                    title:
                        label: slide.label.title
                        property: title
                        width: 10
                    position:
                        label: slide.label.position
                        property: position
                        width: 1
                        widget:
                            type: template
                            template: EnhavoAppBundle:Widget:position.html.twig

enhavo_slider_slide_delete:
    options:
        expose: true
    path: /enhavo/slider/slide/delete/{id}
    methods: [POST, DELETE]
    defaults:
        _controller: enhavo_slider.controller.slide:deleteAction

enhavo_slider_slide_move_after:
    options:
        expose: true
    path: /enhavo/slider/slide/move-after/{id}/{target}
    methods: [POST]
    defaults:
        _controller: enhavo_slider.controller.slide:moveAfterAction
        _sylius:
            sortable_position: position
        _viewer:
            sorting: desc

enhavo_slider_slide_move_to_page:
    options:
        expose: true
    path: /enhavo/slider/slide/move-to-page/{id}/{page}/{top}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_slider.controller.slide:moveToPageAction
        _sylius:
            sortable_position: position
        _viewer:
            sorting: desc
