enhavo_article_article:
    resource: "@EnhavoArticleBundle/Resources/config/routing/admin/article.yml"
    prefix:   /

enhavo_article_tag:
    resource: "@EnhavoArticleBundle/Resources/config/routing/admin/tag.yaml"
    prefix:   /

enhavo_article_category:
    resource: "@EnhavoArticleBundle/Resources/config/routing/admin/category.yaml"
    prefix:   /
