services:
    enhavo_translation.metatdata.collection:
        class: Enhavo\Bundle\TranslationBundle\Metadata\MetadataCollection
        arguments:
            - '@kernel'

    enhavo_translation.translator:
        class: Enhavo\Bundle\TranslationBundle\Translator\Translator
        arguments:
            - '@enhavo_translation.metatdata.collection'
            - '@enhavo_translation.strategy_resolver'
            - '%enhavo_translation.default_locale%'
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_translation.locale_resolver:
        class: Enhavo\Bundle\TranslationBundle\Translator\LocaleResolver
        arguments:
            - '@request_stack'
            - '%enhavo_translation.locales%'
            - '%enhavo_translation.default_locale%'
        calls:
          - [ 'setContainer', ['@service_container']]

    enhavo_translation.strategy_resolver:
        class: Enhavo\Bundle\TranslationBundle\Translator\StrategyResolver
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_translation.strategy.translation_table:
        class: Enhavo\Bundle\TranslationBundle\Translator\Strategy\TranslationTableStrategy
        arguments:
            - '%enhavo_translation.locales%'
            - '@enhavo_translation.locale_resolver'
            - '@doctrine.orm.entity_manager'
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_translation.strategy.route_translation:
        class: Enhavo\Bundle\TranslationBundle\Translator\Strategy\RouteTranslationStrategy
        arguments:
            - '%enhavo_translation.locales%'
            - '@enhavo_translation.locale_resolver'
            - '@doctrine.orm.entity_manager'
            - '@enhavo_app.route_guesser'
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_translation.strategy.slug_translation:
        class: Enhavo\Bundle\TranslationBundle\Translator\Strategy\SlugTranslationStrategy
        arguments:
            - '%enhavo_translation.locales%'
            - '@enhavo_translation.locale_resolver'
            - '@doctrine.orm.entity_manager'
            - '@enhavo_app.route_guesser'
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_translation.doctrine_subscriber:
        class: Enhavo\Bundle\TranslationBundle\EventListener\DoctrineTranslatorSubscriber
        arguments:
            - '@enhavo_translation.translator'
            - '@enhavo_translation.locale_resolver'
        tags:
            - { name: doctrine.event_subscriber, connection: default,  priority: 1000 }

    enhavo_translation.extension.text:
        class: Enhavo\Bundle\TranslationBundle\Form\Extension\TextExtension
        arguments:
            - '@enhavo_translation.translator'
            - '%enhavo_translation.default_locale%'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

    enhavo_translation.extension.translation_data:
        class: Enhavo\Bundle\TranslationBundle\Form\Extension\TranslationDataExtension
        arguments:
            - '@enhavo_translation.translator'
            - '%enhavo_translation.default_locale%'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    enhavo_translation.save_listener:
        class: Enhavo\Bundle\TranslationBundle\EventListener\SaveTranslatorListener
        arguments:
            - '@enhavo_translation.translator'
        tags:
            - { name: kernel.event_listener, event: enhavo_app.post_create, method: postSave }
            - { name: kernel.event_listener, event: enhavo_app.post_update, method: postSave }

    enhavo_translation.preview_listener:
        class: Enhavo\Bundle\TranslationBundle\EventListener\PreviewListener
        arguments:
            - '@enhavo_translation.locale_resolver'
        tags:
            - { name: kernel.event_listener, event: enhavo_app.init_preview, method: onInitPreview }

    enhavo_translation.menu.translation:
        class: Enhavo\Bundle\TranslationBundle\Menu\TranslationStringMenu
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: translation }

    enhavo_translation_translation_string:
        class: '%enhavo_translation.form.type.translation_string.class%'
        arguments:
            - '%enhavo_translation.translate%'
        tags:
            - { name: form.type }

    enhavo_translation.listener.locale_listener:
        class: Enhavo\Bundle\TranslationBundle\EventListener\LocaleListener
        arguments:
            - '@enhavo_translation.locale_resolver'
        tags:
            - { name: kernel.event_subscriber }

    enhavo_translation.slug_translator:
        class: Enhavo\Bundle\TranslationBundle\Translator\SlugTranslator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@enhavo_translation.locale_resolver'

    enhavo_translation.twig.translate_string:
        class: Enhavo\Bundle\TranslationBundle\Twig\TranslateString
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_translation.twig.locale:
        class: Enhavo\Bundle\TranslationBundle\Twig\Locale
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, ['@service_container']]

    enhavo_translation.translation_route_manager:
        class: Enhavo\Bundle\TranslationBundle\Route\TranslationRouteManager
        arguments:
            - '@enhavo_app.route_manager'
            - '@doctrine.orm.entity_manager'

    enhavo_translation.translate_string.translator:
        class: Enhavo\Bundle\TranslationBundle\TranslationString\TranslateStringTranslator
        arguments:
            - '@enhavo_translation.repository.translation_string'

