services:
    enhavo_app.action_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'Action'

    enhavo_app.action_manager:
        class: Enhavo\Bundle\AppBundle\Action\ActionManager
        arguments:
            - '@enhavo_app.action_collector'
            - '@security.authorization_checker'

    enhavo_app.action_language_expression:
        class: Enhavo\Bundle\AppBundle\Action\ActionLanguageExpression
        arguments:
            - '@sylius.expression_language'
        calls:
            - [ 'addVariable', [ 'authorizationChecker', '@security.authorization_checker' ] ]
            - [ 'addVariable', [ 'tokenStorage', '@security.token_storage' ] ]
            - [ 'addVariable', [ 'requestStack', '@request_stack' ] ]

    Enhavo\Bundle\AppBundle\Action\AbstractActionType:
        abstract: true
        arguments:
            - '@translator'
            - '@enhavo_app.action_language_expression'

    Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractActionType
        abstract: true
        arguments:
            - '@router'

    Enhavo\Bundle\AppBundle\Action\Type\CreateActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: create }

    Enhavo\Bundle\AppBundle\Action\Type\DownloadActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: download }

    Enhavo\Bundle\AppBundle\Action\Type\OpenActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: open }
              
    Enhavo\Bundle\AppBundle\Action\Type\DeleteActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        arguments:
            - '@security.csrf.token_manager'
        public: true
        tags:
            - { name: enhavo.action, alias: delete }

    Enhavo\Bundle\AppBundle\Action\Type\CloseActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractActionType
        public: true
        tags:
            - { name: enhavo.action, alias: close }

    Enhavo\Bundle\AppBundle\Action\Type\PreviewActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: preview }

    Enhavo\Bundle\AppBundle\Action\Type\SaveActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: save }

    Enhavo\Bundle\AppBundle\Action\Type\DuplicateActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: duplicate }

    Enhavo\Bundle\AppBundle\Action\Type\EventActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractActionType
        public: true
        tags:
            - { name: enhavo.action, alias: event }

    Enhavo\Bundle\AppBundle\Action\Type\FormActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: form }

    Enhavo\Bundle\AppBundle\Action\Type\FilterActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractActionType
        public: true
        tags:
            - { name: enhavo.action, alias: filter }

    Enhavo\Bundle\AppBundle\Action\Type\UpdateActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: update }

    Enhavo\Bundle\AppBundle\Action\Type\TransitionActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: transition }

    Enhavo\Bundle\AppBundle\Action\Type\ModalActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractActionType
        public: true
        tags:
            - { name: enhavo.action, alias: modal }

    Enhavo\Bundle\AppBundle\Action\Type\OutputStreamActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractUrlActionType
        public: true
        tags:
            - { name: enhavo.action, alias: output_stream }

    Enhavo\Bundle\AppBundle\Action\Type\DropdownActionType:
        parent: Enhavo\Bundle\AppBundle\Action\AbstractActionType
        arguments:
            - '@enhavo_app.action_manager'
        public: true
        tags:
            - { name: enhavo.action, alias: dropdown }
