parameters:
    security.roles.provider.class: Enhavo\Bundle\AppBundle\Security\Roles\AdminRolesProvider

services:
    enhavo_app.cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ['%kernel.cache_dir%/cache']

    security.roles.provider:
        class: '%security.roles.provider.class%'
        arguments:
            - '%enhavo_app.roles%'
            - '@translator'

    enhavo_app.event_dispatcher:
        class: Enhavo\Bundle\AppBundle\Controller\AppEventDispatcher
        arguments:
            - '@event_dispatcher'

    enhavo_app.preview.default_renderer:
        class: Enhavo\Bundle\AppBundle\Preview\DefaultRenderer
        public: true

    enhavo_app.preview.strategy_resolver:
        class: Enhavo\Bundle\AppBundle\Preview\StrategyResolver
        calls:
            - ['setContainer', ['@service_container']]

    enhavo_app.preview.strategy.dynamic:
        class: Enhavo\Bundle\AppBundle\Preview\Strategy\DynamicStrategy
        public: true
        calls:
            - ['setContainer', ['@service_container']]

    enhavo_app.preview.strategy.service:
        class: Enhavo\Bundle\AppBundle\Preview\Strategy\ServiceStrategy
        public: true
        arguments:
            - '@enhavo_app.argument_resolver'
            - '@request_stack'
        calls:
            - ['setContainer', ['@service_container']]

    security.authentication.voter.super_admin:
        class: Enhavo\Bundle\AppBundle\Security\Authentication\Voter\SuperAdminVoter
        tags:
            - { name: security.voter }

    enhavo.sorting_manager:
        class: Enhavo\Bundle\AppBundle\Controller\SortingManager
        arguments:
            - '@doctrine.orm.entity_manager'

    enhavo_app.factory.duplicate_resource_factory:
        class: Enhavo\Bundle\AppBundle\Controller\DuplicateResourceFactory

    enhavo_app.security.default_authorization_checker:
        class: Enhavo\Bundle\AppBundle\Security\AuthorizationChecker\SymfonyAuthorizationChecker
        arguments:
            - '@security.authorization_checker'

    enhavo_app.util.secure_url_token_generator:
        class: Enhavo\Bundle\AppBundle\Util\SecureUrlTokenGenerator

    enhavo_app.util.doctrine_reference_finder:
        class: Enhavo\Bundle\AppBundle\Util\DoctrineReferenceFinder
        arguments:
            - '@doctrine.orm.entity_manager'

    enhavo_app.translation.translation_dumper:
        public: true
        class: Enhavo\Bundle\AppBundle\Translation\TranslationDumper
        arguments:
            - []

    enhavo_app.template.manager:
        public: true
        class: Enhavo\Bundle\AppBundle\Template\TemplateManager
        arguments:
            - '@kernel'
            - '@filesystem'
            - '@enhavo_app.template.config_webpack_build_resolver'
            - '%enhavo_app.template_paths%'
            - '%twig.default_path%'

    enhavo_app.template.config_webpack_build_resolver:
        class: Enhavo\Bundle\AppBundle\Template\ConfigWebpackBuildResolver
        arguments:
            - '%enhavo_app.webpack_build%'

    enhavo_app.argument_resolver:
        class: Enhavo\Bundle\AppBundle\Controller\ArgumentResolver
        arguments:
            - '@argument_metadata_factory'
