parameters:
    security.roles.provider.class: Enhavo\Bundle\AppBundle\Security\Roles\AdminRolesProvider

services:
    enhavo_app.cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ['%kernel.cache_dir%/cache']

    security.roles.provider:
        class: '%security.roles.provider.class%'
        arguments:
            - '%enhavo_app.roles%'
            - '@translator'

    enhavo_app.controller.app:
        class: Enhavo\Bundle\AppBundle\Controller\AppController
        public: true
        arguments:
            - '@view.factory'
            - '@fos_rest.view_handler'
        calls:
            - [setContainer, ['@service_container']]

    enhavo_app.event_dispatcher:
        class: Enhavo\Bundle\AppBundle\Controller\AppEventDispatcher
        arguments:
            - '@event_dispatcher'

    enhavo_app.controller.auto_complete:
        class: Enhavo\Bundle\AppBundle\Controller\AutoCompleteController
        arguments:
            - '@sylius.expression_language'
        public: true
        calls:
            - [setContainer, ['@service_container']]

    enhavo_app.preview.default_renderer:
        class: Enhavo\Bundle\AppBundle\Preview\DefaultRenderer
        public: true

    enhavo_app.preview.strategy_resolver:
        class: Enhavo\Bundle\AppBundle\Preview\StrategyResolver
        arguments:
            - '@service_container'

    enhavo_app.preview.strategy.dynamic:
        class: Enhavo\Bundle\AppBundle\Preview\Strategy\DynamicStrategy
        public: true
        arguments:
            - '@service_container'

    enhavo_app.preview.strategy.service:
        class: Enhavo\Bundle\AppBundle\Preview\Strategy\ServiceStrategy
        public: true
        arguments:
            - '@service_container'

    security.authentication.voter.super_admin:
        class: Enhavo\Bundle\AppBundle\Security\Authentication\Voter\SuperAdminVoter
        tags:
            - { name: security.voter }

    enhavo.sorting_manager:
        class: Enhavo\Bundle\AppBundle\Controller\SortingManager
        arguments:
            - '@doctrine.orm.entity_manager'

    enhavo.translation.locale_provider.contextual:
        class: Enhavo\Bundle\AppBundle\Provider\TranslationLocaleProvider
        arguments:
            - '%locale%'

    enhavo_app.factory.duplicate_resource_factory:
        class: Enhavo\Bundle\AppBundle\Controller\DuplicateResourceFactory

    enhavo_app.formatter.currency_formatter:
        class: Enhavo\Bundle\AppBundle\Formatter\CurrencyFormatter

    enhavo_app.security.default_authorization_checker:
        class: Enhavo\Bundle\AppBundle\Security\AuthorizationChecker\SymfonyAuthorizationChecker
        arguments:
            - '@security.authorization_checker'

    enhavo_app.twig.currency:
        class: Enhavo\Bundle\AppBundle\Twig\Currency
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    enhavo_app.util.secure_url_token_generator:
        class: Enhavo\Bundle\AppBundle\Util\SecureUrlTokenGenerator