services:
    Enhavo\Bundle\AppBundle\Twig\PaginationExtension:
        arguments:
            - 'EnhavoAppBundle:View:pagination.html.twig'
        calls:
            - [ setEngine, ['@templating']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\BrandingExtension:
        arguments:
            - '%enhavo_app.branding%'
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\TemplateExtension:
        arguments:
            - '%enhavo_app.form_themes%'
            - '@enhavo_app.template.manager'
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\SplObjectExtension:
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\WidgetExtension:
        arguments:
            - '@enhavo_app.widget.widget_manager'
            - '@enhavo_app.template.manager'
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\RouteExtension:
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: twig.extension }