services:
    Enhavo\Bundle\AppBundle\Twig\PaginationExtension:
        arguments:
            - 'EnhavoAppBundle:View:pagination.html.twig'
        calls:
            - [ setTwigEnvironment, ['@twig']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\BrandingExtension:
        arguments:
            - '%enhavo_app.branding%'
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\TemplateExtension:
        arguments:
            - '%enhavo_app.form_themes%'
            - '@Enhavo\Bundle\AppBundle\Template\TemplateResolverInterface'
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\SplObjectExtension:
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\WidgetExtension:
        arguments:
            - '@enhavo_app.widget.widget_manager'
            - '@Enhavo\Bundle\AppBundle\Template\TemplateResolverInterface'
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\RouteExtension:
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: twig.extension }

    Enhavo\Bundle\AppBundle\Twig\LocaleExtension:
        arguments:
            - '@enhavo_app.locale_resolver'
        tags:
            - { name: twig.extension }