services:
    enhavo_app.widget_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'Widget'

    enhavo_app.widget.widget_manager:
        class: Enhavo\Bundle\AppBundle\Widget\WidgetManager
        arguments:
            - '@enhavo_app.widget_collector'

    Enhavo\Bundle\AppBundle\Widget\Type\TemplateType:
        public: true
        tags:
            - { name: enhavo.widget, alias: template }

    Enhavo\Bundle\AppBundle\Widget\Type\PaginationWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: 'pagination' }