Enhavo\Bundle\ContentBundle\Entity\Content:
    type: entity
    table: content_content
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToMany:
        containers:
            targetEntity: Container
            mappedBy: content
            cascade: ['persist', 'refresh', 'remove']

        items:
            targetEntity: Item
            mappedBy: content
            cascade: ['persist', 'refresh', 'remove']
            orderBy:
                order: ASC

    lifecycleCallbacks: {  }
