services:
    Enhavo\Bundle\CalendarBundle\Form\Type\AppointmentType:
        arguments:
            - '%enhavo_calendar.model.appointment.class%'
            - [default]
            - '%enhavo_app.translate%'
        tags:
            - { name: form.type, alias: enhavo_calendar_appointment }

    validator.appointment_date:
        class:  Enhavo\Bundle\CalendarBundle\Validator\Constraints\AppointmentDateValidator
        arguments:
            - '@service_container'
        tags:
            - { name: validator.constraint_validator, alias: valid_appointment_date }

    enhavo_calendar.extend_listener.appointment:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\CalendarBundle\Entity\Appointment
            - '%enhavo_calendar.model.appointment.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Enhavo\Bundle\CalendarBundle\Menu\CalendarMenu:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: calendar }

    enhavo_calendar.import_manager:
        class: Enhavo\Bundle\CalendarBundle\Import\ImportManager
        arguments:
            - '%enhavo_calendar.imports%'
            - '@service_container'

    enhavo_calendar.exporter:
        class: Enhavo\Bundle\CalendarBundle\Export\CalendarExporter
        arguments:
            - '%enhavo_calendar.export_name%'
            - '@doctrine.orm.entity_manager'

    enhavo_calendar.appointment_provider:
        class: Enhavo\Bundle\CalendarBundle\Provider\AppointmentProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    Enhavo\Bundle\CalendarBundle\Command\ImportCommand:
        arguments:
            - '@enhavo_calendar.import_manager'
        tags:
            - { name: console.command, command: 'enhavo:calendar:import' }

    Enhavo\Bundle\CalendarBundle\Block\CalendarBlockType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.block, alias: calendar }
