enhavo_app:
    template_paths:
        enhavo_setting:
            path: '@EnhavoSettingBundle/Resources/views'
            priority: 10
    roles:
        enhavo_setting_setting_index:
            role: ROLE_ENHAVO_SETTING_SETTING_INDEX
            label: setting.role.label.index
            translationDomain: EnhavoSettingBundle
        enhavo_setting_setting_update:
            role: ROLE_ENHAVO_SETTING_SETTING_UPDATE
            label: setting.role.label.update
            translationDomain: EnhavoSettingBundle