enhavo_workflow_workflow_index:
    options:
        expose: true
    path: /enhavo/workflow/workflow/index
    methods: [GET]
    defaults:
        _controller: enhavo_workflow.controller.workflow:indexAction
        _sylius:
            template: EnhavoAppBundle:Resource:index.html.twig
        _viewer:

enhavo_workflow_workflow_create:
    options:
        expose: true
    path: /enhavo/workflow/workflow/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_workflow.controller.workflow:createAction
        _sylius:
            template: EnhavoAppBundle:Resource:create.html.twig
        _viewer:
            translationDomain: EnhavoWorkflowBundle
            tabs:
                workflow:
                    label: workflow.label.workflow
                    template: EnhavoWorkflowBundle:Tab:workflowCreate.html.twig
                node:
                    label: workflow.label.nodes
                    template: EnhavoWorkflowBundle:Tab:nodes.html.twig

enhavo_workflow_workflow_update:
    options:
        expose: true
    path: /enhavo/workflow/workflow/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_workflow.controller.workflow:updateAction
        _sylius:
            template: EnhavoAppBundle:Resource:update.html.twig
        _viewer:
            translationDomain: EnhavoWorkflowBundle
            tabs:
                workflow:
                    label: workflow.label.workflow
                    template: EnhavoWorkflowBundle:Tab:workflowEdit.html.twig
                node:
                    label: workflow.label.nodes
                    template: EnhavoWorkflowBundle:Tab:nodes.html.twig
                transition:
                    label: workflow.label.transitions
                    template: EnhavoWorkflowBundle:Tab:transitions.html.twig


enhavo_workflow_workflow_table:
    options:
        expose: true
    path: /enhavo/workflow/workflow/table/{page}
    methods: [GET]
    defaults:
        page: 1
        _controller: enhavo_workflow.controller.workflow:tableAction
        _sylius:
            template: EnhavoAppBundle:Resource:table.html.twig
        _viewer:
            translationDomain: EnhavoWorkflowBundle
            table:
                columns:
                    id:
                        label: workflow.label.id
                        property: id
                        width: 1
                    workflow_name:
                        label: workflow.label.workflowName
                        property: workflowName
                        width: 7
                    entity:
                        label: workflow.label.entity
                        property: entity
                        width: 4

enhavo_workflow_workflow_delete:
    options:
        expose: true
    path: /enhavo/workflow/workflow/delete/{id}
    methods: [DELETE]
    defaults:
        _controller: enhavo_workflow.controller.workflow:deleteAction

enhavo_workflow_workflow_preview:
    options:
        expose: true
    path: /enhavo/workflow/workflow/preview
    methods: [POST]
    defaults:
        _controller: enhavo_workflow.controller.workflow:previewAction
