Sylius\Component\Order\Model\Order:
    attributes:
        items:
            groups: ['cart']

Enhavo\Bundle\ShopBundle\Entity\Voucher:
    attributes:
        id:
            groups: [ 'cart' ]
        code:
            groups: ['cart']

Enhavo\Bundle\ShopBundle\Entity\Order:
    attributes:
        vouchers:
            groups: ['cart']
        items:
            groups: ['cart']
        totalQuantity:
            groups: ['cart']
        total:
            groups: ['cart']

Enhavo\Bundle\ShopBundle\Entity\OrderItem:
    attributes:
        id:
            groups: ['cart']
        name:
            groups: ['cart']
        product:
            groups: ['cart']
        quantity:
            groups: ['cart']
        unitPrice:
            groups: ['cart']
        unitPriceTotal:
            groups: ['cart']
        total:
            groups: ['cart']
