services:
    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceIndexEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Grid\GridFactory'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceListEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Grid\GridFactory'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceCreateEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Input\InputFactory'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
            - '@Enhavo\Bundle\VueFormBundle\Form\VueForm'
            - '@Enhavo\Bundle\ResourceBundle\RouteResolver\RouteResolverInterface'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceUpdateEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Input\InputFactory'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
            - '@Enhavo\Bundle\VueFormBundle\Form\VueForm'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceBatchEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
            - '@Enhavo\Bundle\ResourceBundle\Grid\GridFactory'
            - '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceDeleteEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Input\InputFactory'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
            - '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceDuplicateEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Input\InputFactory'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
            - '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
            - '@Enhavo\Bundle\ResourceBundle\RouteResolver\RouteResolverInterface'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }