doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\SidebarBundle\Model\SidebarInterface: Enhavo\Bundle\SidebarBundle\Entity\Sidebar

enhavo_app:
    template_paths:
        enhavo_sidebar:
            path: '@EnhavoSidebarBundle/Resources/views'
            alias: EnhavoSidebar
            priority: 10
    roles:
        enhavo_sidebar_sidebar_index:
            role: ROLE_ENHAVO_SIDEBAR_SIDEBAR_INDEX
            label: sidebar.role.label.index
            translation_domain: EnhavoSidebarBundle
        enhavo_sidebar_sidebar_create:
            role: ROLE_ENHAVO_SIDEBAR_SIDEBAR_CREATE
            label: sidebar.role.label.create
            translation_domain: EnhavoSidebarBundle
        enhavo_sidebar_sidebar_update:
            role: ROLE_ENHAVO_SIDEBAR_SIDEBAR_UPDATE
            label: sidebar.role.label.update
            translation_domain: EnhavoSidebarBundle
        enhavo_sidebar_sidebar_delete:
            role: ROLE_ENHAVO_SIDEBAR_SIDEBAR_DELETE
            label: sidebar.role.label.delete
            translation_domain: EnhavoSidebarBundle