enhavo_user_group_index:
    options:
        expose: true
    path: /enhavo/user/group/index
    methods: [GET]
    defaults:
        _controller: enhavo_user.controller.group:indexAction
        _sylius:
            template: EnhavoAppBundle:Resource:index.html.twig
        _viewer:
            title: group.label.group
            translationDomain: EnhavoUserBundle

enhavo_user_group_create:
    options:
        expose: true
    path: /enhavo/user/group/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_user.controller.group:createAction
        _sylius:
            template: EnhavoAppBundle:Resource:create.html.twig
        _viewer:
             translationDomain: EnhavoUserBundle

enhavo_user_group_update:
    options:
        expose: true
    path: /enhavo/user/group/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_user.controller.group:updateAction
        _sylius:
            template: EnhavoAppBundle:Resource:update.html.twig
        _viewer:
             translationDomain: EnhavoUserBundle

enhavo_user_group_table:
    options:
        expose: true
    path: /enhavo/user/group/table/{page}
    methods: [GET]
    defaults:
        page: 1
        _controller: enhavo_user.controller.group:tableAction
        _sylius:
            template: EnhavoAppBundle:Resource:table.html.twig
        _viewer:
            translationDomain: EnhavoUserBundle
            table:
                columns:
                    id:
                        label: group.label.id
                        property: id
                    name:
                        label: group.label.name
                        property: name


enhavo_user_group_delete:
    options:
        expose: true
    path: /enhavo/user/group/delete/{id}
    methods: [POST, DELETE]
    defaults:
        _controller: enhavo_user.controller.group:deleteAction

enhavo_user_group_batch:
    options:
        expose: true
    path: /enhavo/user/group/batch
    methods: [POST]
    defaults:
        _controller: enhavo_user.controller.group:batchAction
