enhavo_user_user_index:
    options:
        expose: true
    path: /enhavo/user/user/index
    methods: [GET]
    defaults:
        _controller: enhavo_user.controller.user:indexAction
        _sylius:
            viewer:
                title: user.label.user
                translationDomain: EnhavoUserBundle

enhavo_user_user_create:
    options:
        expose: true
    path: /enhavo/user/user/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_user.controller.user:createAction
        _sylius:
            viewer:
                translationDomain: EnhavoUserBundle

enhavo_user_user_update:
    options:
        expose: true
    path: /enhavo/user/user/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_user.controller.user:updateAction
        _sylius:
            viewer:
                translationDomain: EnhavoUserBundle

enhavo_user_user_table:
    options:
        expose: true
    path: /enhavo/user/user/table
    methods: [GET]
    defaults:
        _controller: enhavo_user.controller.user:tableAction
        _sylius:
            viewer:
                translationDomain: EnhavoUserBundle
                columns:
                    id:
                        label: user.label.id
                        property: id
                    username:
                        label: user.label.username
                        property: username
                        width: 6
                    groups:
                        type: list
                        label: group.label.group
                        property: groups
                        item_property: name
                        width: 5

enhavo_user_user_delete:
    options:
        expose: true
    path: /enhavo/user/user/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_user.controller.user:deleteAction

enhavo_user_user_batch:
    options:
        expose: true
    path: /enhavo/user/user/batch
    methods: [POST]
    defaults:
        _controller: enhavo_user.controller.user:batchAction
