parameters:
    enhavo_contact.form.contact.class: Enhavo\Bundle\ContactBundle\Form\Type\ContactFormType
    enhavo_contact.model.contact.class: Enhavo\Bundle\ContactBundle\Model\Contact

services:
    enhavo_contact.form.contact:
        class: '%enhavo_contact.form.contact.class%'
        arguments:
            - '%enhavo_contact.model.contact.class%'
        tags:
            - { name: form.type, alias: 'enhavo_contact_contact' }

    enhavo_contact.configuration.factory:
        class: Enhavo\Bundle\ContactBundle\Configuration\ConfigurationFactory
        calls:
            - [setContainer, ['@service_container']]

    Enhavo\Bundle\ContactBundle\Widget\ContactWidget:
        public: true
        arguments:
            - '@enhavo_contact.configuration.factory'
            - '@form.factory'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: 'contact' }

    enhavo_contact.mailer:
        class: Enhavo\Bundle\ContactBundle\Mailer\ContactMailer
        arguments:
            - '@enhavo_contact.configuration.factory'
            - '@templating'
            - '@translator'
            - '@mailer'

    enhavo_contact.form_error_resolver:
        class: Enhavo\Bundle\ContactBundle\ErrorResolver\FormErrorResolver
        arguments:
            - '@translator'

    enhavo_contact.controller.contact:
        class: Enhavo\Bundle\ContactBundle\Controller\ContactController
        arguments:
            - '@translator'
            - '@enhavo_contact.mailer'
            - '@enhavo_contact.configuration.factory'
            - '@enhavo_contact.form_error_resolver'
            - '@sylius.resource_controller.request_configuration_factory'
        calls:
            - [setContainer, ['@service_container']]