parameters:
    enhavo_content.form.type.content.class: Enhavo\Bundle\ContentBundle\Form\Type\ContentType

services:
    enhavo_content_content:
        class: '%enhavo_content.form.type.content.class%'
        arguments:
            - '%enhavo_app.translate%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\ContentBundle\Batch\PublishBatch:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.batch, alias: publish }

    enhavo_content.sitemap_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'SitemapCollector'

    enhavo_content.sitemap.generator:
        class: Enhavo\Bundle\ContentBundle\Sitemap\SitemapGenerator
        arguments:
            - '%enhavo_content.sitemap.collectors%'
            - '@enhavo_content.sitemap_collector'

    enhavo_content.sitemap_collector.repository:
        class: Enhavo\Bundle\ContentBundle\Sitemap\Collector\RepositoryCollector
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            - '@enhavo_routing.router'
        tags:
            - { name: enhavo.sitemap_collector, alias: repository }

    enhavo_content.sitemap_collector.publish:
        class: Enhavo\Bundle\ContentBundle\Sitemap\Collector\PublishCollector
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            - '@enhavo_routing.router'
        tags:
            - { name: enhavo.sitemap_collector, alias: publish }

    enhavo_content.sitemap_collector.configuration:
        class: Enhavo\Bundle\ContentBundle\Sitemap\Collector\ConfigurationCollector
        tags:
            - { name: enhavo.sitemap_collector, alias: configuration }

    enhavo_content.event_listener.publish_subscriber:
        class: Enhavo\Bundle\ContentBundle\EventListener\PublishSubscriber
        tags:
            - { name: kernel.event_subscriber }

    Enhavo\Bundle\ContentBundle\Widget\PaginationWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: 'pagination' }

    Enhavo\Bundle\ContentBundle\Menu\RedirectMenu:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: redirect }

    enhavo_content.redirect.redirect_manager:
        class: Enhavo\Bundle\ContentBundle\Redirect\RedirectManager
        arguments:
            - '@enhavo_routing.manager.route'

    enhavo_content.event_listener.redirect_subscriber:
        class: Enhavo\Bundle\ContentBundle\EventListener\RedirectSubscriber
        arguments:
            - '@enhavo_content.redirect.redirect_manager'
        tags:
            - { name: kernel.event_subscriber }
