parameters:
    enhavo_content.form.type.content.class: Enhavo\Bundle\ContentBundle\Form\Type\ContentType

services:
    enhavo_content_content:
        class: '%enhavo_content.form.type.content.class%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\ContentBundle\Batch\PublishBatchType:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: enhavo_app.batch }

    enhavo_content.sitemap_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'SitemapCollector'

    enhavo_content.sitemap.generator:
        class: Enhavo\Bundle\ContentBundle\Sitemap\SitemapGenerator
        arguments:
            - '%enhavo_content.sitemap.collectors%'
            - '@enhavo_content.sitemap_collector'

    enhavo_content.sitemap_collector.repository:
        public: true
        class: Enhavo\Bundle\ContentBundle\Sitemap\Collector\RepositoryCollector
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            - '@enhavo_routing.router'
        tags:
            - { name: enhavo.sitemap_collector, alias: repository }

    enhavo_content.sitemap_collector.publish:
        public: true
        class: Enhavo\Bundle\ContentBundle\Sitemap\Collector\PublishCollector
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            - '@enhavo_routing.router'
        tags:
            - { name: enhavo.sitemap_collector, alias: publish }

    enhavo_content.sitemap_collector.configuration:
        public: true
        class: Enhavo\Bundle\ContentBundle\Sitemap\Collector\ConfigurationCollector
        tags:
            - { name: enhavo.sitemap_collector, alias: configuration }

    enhavo_content.event_listener.publish_subscriber:
        class: Enhavo\Bundle\ContentBundle\EventListener\PublishSubscriber
        tags:
            - { name: kernel.event_subscriber }

    Enhavo\Bundle\ContentBundle\EventListener\SaveSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    Enhavo\Bundle\ContentBundle\Controller\SitemapController:
        arguments:
            - '@enhavo_content.sitemap.generator'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Enhavo\Bundle\ContentBundle\Command\SitemapDumpCommand:
        arguments:
            - '@enhavo_content.sitemap.generator'
            - '@filesystem'
            - 'public/sitemap.xml'
            - '%kernel.project_dir%'
        tags:
            - { name: console.command }

    Enhavo\Bundle\ContentBundle\Factory\VideoFactory:
        public: true
        calls:
            - ['addProvider', ['@Enhavo\Bundle\ContentBundle\Video\VimeoProvider']]
            - ['addProvider', ['@Enhavo\Bundle\ContentBundle\Video\YoutubeProvider']]

    Enhavo\Bundle\ContentBundle\Video\VimeoProvider:
        arguments:
            - '%enhavo_content.video.vimeo.api_key%'

    Enhavo\Bundle\ContentBundle\Video\YoutubeProvider:
        arguments:
            - '%enhavo_content.video.youtube.api_key%'
