enhavo_calendar_admin_api_appointment_index:
    path: /appointment/index
    methods:
        - GET
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_index
            grid: enhavo_calendar.appointment

enhavo_calendar_admin_api_appointment_list:
    path: /appointment/list
    methods:
        - GET
        - POST
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_list
            grid: enhavo_calendar.appointment

enhavo_calendar_admin_api_appointment_create:
    path: /appointment/create
    methods:
        - GET
        - POST
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_create
            input: enhavo_calendar.appointment

enhavo_calendar_admin_api_appointment_update:
    path: '/appointment/update/{id}'
    methods:
        - GET
        - POST
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_update
            input: enhavo_calendar.appointment

enhavo_calendar_admin_api_appointment_delete:
    path: '/appointment/delete/{id}'
    methods:
        - DELETE
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_delete
            input: enhavo_calendar.appointment

enhavo_calendar_admin_api_appointment_preview:
    path: /appointment/preview
    methods: [POST]
    defaults:
        _expose: admin_api
        _area: theme
        _endpoint:
            type: preview
            input: enhavo_calendar.appointment
            endpoint:
                type: Enhavo\Bundle\CalendarBundle\Endpoint\AppointmentEndpointType
                resource: expr:resource
                preview: true
