parameters:
    # keep for bc breaks with other bundles
    locale: '%kernel.default_locale%'

framework:
    translator: { fallback: "%env(string:APP_DEFAULT_LOCALE)%" }
    validation:
        enabled: true
    session:
        cookie_lifetime: 25920000
    templating:
        engines: twig

doctrine:
    dbal:
        mapping_types:
            enum: string
            json: string
            json_array: string

stof_doctrine_extensions:
    default_locale: "%env(string:APP_DEFAULT_LOCALE)%"
    orm:
        default:
            sluggable: true
            timestampable: true

sylius_resource:
    authorization_checker: enhavo_app.security.default_authorization_checker

jms_serializer:
    metadata:
        auto_detection: false

enhavo_app:
    locale: "%env(string:APP_DEFAULT_LOCALE)%"
    template_paths:
        default:
            path: ''
            priority: 150
        enhavo_app:
            path: '@EnhavoAppBundle/Resources/views'
            priority: 10
