framework:
    translator: { fallback: "%locale%" }
    validation:
        enabled: true
    session:
        cookie_lifetime: 25920000

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            sluggable: true
            timestampable: true

sylius_resource:
    authorization_checker: enhavo_app.security.default_authorization_checker

jms_serializer:
    metadata:
        auto_detection: false

enhavo_app:
    locale: "%locale%"
    template_paths:
        enhavo_app:
            path: '@EnhavoAppBundle/Resources/views'
            alias: 'EnhavoApp'
            priority: 10
    admin:
#        form_mapping:
#            form-row: form-admin-row
#            form-widget': form-admin-widget
    area:
        theme:
            firewall: main
            options:
                routes: ['api', 'theme']
                vue_routes: ['theme']
                navigation: true
        api:
            path: ^/api/
        admin:
            firewall: admin
            path:
                - ^/admin/reset-password/.+
                - ^/admin/login$
            options:
                routes: ['admin', 'admin_api']
                vue_routes: ['admin']
                translations: ['messages', 'javascript']
        admin_api:
            path: ^/admin/api/
