services:
    Enhavo\Bundle\DoctrineExtensionBundle\EventListener\ReferenceSubscriber:
        arguments:
            - '@Enhavo\Component\Metadata\MetadataRepository[DoctrineExtension]'
            - '@Enhavo\Bundle\DoctrineExtensionBundle\EntityResolver\EntityResolverInterface'
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }
            - { name: doctrine.event_listener, event: postFlush, method: postFlush }

    Enhavo\Bundle\DoctrineExtensionBundle\EventListener\ExtendSubscriber:
        arguments:
            - '@Enhavo\Component\Metadata\MetadataRepository[DoctrineExtension]'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, method: loadClassMetadata, priority: 1000 }