Enhavo\Bundle\NewsletterBundle\Entity\Subscriber:
    type: entity
    table: newsletter_subscriber
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        email:
            type: string
            lenght: 255
            nullable: true

        active:
            type: boolean
            nullable: true

        activatedAt:
            type: datetime
            nullable: true

        createdAt:
            type: datetime
            nullable: true

        token:
            type: string
            lenght: 255
            nullable: true

    manyToMany:
        groups:
            targetEntity: Enhavo\Bundle\NewsletterBundle\Model\GroupInterface
            joinTable:
                name: newsletter_subscriber_group
                joinColumns:
                    subscriber_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
