services:
    Enhavo\Bundle\UserBundle\Controller\RegistrationController:
        public: true
        arguments:
            - '@Enhavo\Bundle\UserBundle\User\UserManager'
            - '@Enhavo\Bundle\UserBundle\Configuration\ConfigurationProvider'
            - '@enhavo_user.repository.user'
            - '@enhavo_user.factory.user'
            - '@enhavo_form.error.error.resolver'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: controller.service_arguments }

    Enhavo\Bundle\UserBundle\Controller\ResetPasswordController:
        public: true
        arguments:
            - '@Enhavo\Bundle\UserBundle\User\UserManager'
            - '@Enhavo\Bundle\UserBundle\Configuration\ConfigurationProvider'
            - '@enhavo_user.repository.user'
            - '@enhavo_user.factory.user'
            - '@translator'
            - '@Enhavo\Bundle\FormBundle\Error\FormErrorResolver'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }

    Enhavo\Bundle\UserBundle\Controller\ChangeEmailController:
        public: true
        arguments:
            - '@Enhavo\Bundle\UserBundle\User\UserManager'
            - '@Enhavo\Bundle\UserBundle\Configuration\ConfigurationProvider'
            - '@enhavo_user.repository.user'
            - '@enhavo_user.factory.user'
            - '@translator'
            - '@Enhavo\Bundle\FormBundle\Error\FormErrorResolver'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }

    Enhavo\Bundle\UserBundle\Controller\SecurityController:
        public: true
        arguments:
            - '@Enhavo\Bundle\UserBundle\User\UserManager'
            - '@Enhavo\Bundle\UserBundle\Configuration\ConfigurationProvider'
            - '@security.csrf.token_manager'
            - '@translator'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }

    Enhavo\Bundle\UserBundle\Controller\ChangePasswordController:
        public: true
        arguments:
            - '@Enhavo\Bundle\UserBundle\User\UserManager'
            - '@Enhavo\Bundle\UserBundle\Configuration\ConfigurationProvider'
            - '@fos_rest.view_handler'
            - '@view.factory'
            - '@translator'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }

    Enhavo\Bundle\UserBundle\Controller\ProfileController:
        public: true
        arguments:
            - '@Enhavo\Bundle\UserBundle\User\UserManager'
            - '@Enhavo\Bundle\UserBundle\Configuration\ConfigurationProvider'
            - '@translator'
            - '@Enhavo\Bundle\FormBundle\Error\FormErrorResolver'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }
